### ISSUE TITLE
Bug: dry SQL mapper not empty

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#102]
When calling `load()` multiples times, SQL mapper values are not reset if no record is returned:
```php
// First, load an existing record
$mapper->load('id=1');
echo $mapper->dry();// FALSE
echo $mapper->title;// Title1

// Then try to load an unexisting record
$mapper->load('id=2');
echo $mapper->dry();// TRUE
echo $mapper->title;// Title1
print_r($mapper->cast());// values of the first record
```

I'm not sure where to fix it.

**Comment by KOTRET** [comment]
what about calling
```php
	function reset() {
		$this->query=array();
		$this->ptr=0;
	}
```
in `load` instead of just manually resetting `ptr` with
```php
$this->ptr=0;
```

**Comment by xfra35** [comment]
That makes totally sense.
Thanks for the suggestion :+1:

**Comment by KOTRET** [comment]
any unit tests? :relieved:

**Comment by xfra35** [comment]
Really? I've replaced `$this->ptr=0;` with `$this->query=array();$this->ptr=0;`
