### ISSUE TITLE
DB mapper: onload event

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#103]
It just occurred to me that the `onload` event seems to overtrigger.

See:

``` php
$mapper=new DB\SQL\Mapper($db,'mytable');// 3 record ids: 1,2,3
$mapper->onload(function($me){
  echo $me->id.',';
});
$mapper->load();// output: 1,2,3,1,
$mapper->next();// output: 2,
$mapper->next();// output: 3,
```

This behaviour is due to the fact that both `skip()` and `factory()` trigger that event. I think we should trigger it in one single place.

**Comment by KOTRET** [comment]
imho only in factory, because you can call next / prev several times and don't want to trigger the onload again, do you? This depends on how to use the mapper (fetching all or iterating through a query result) ?

**Comment by xfra35** [comment]
I also think that it belongs to `factory`. But let's wait a bit to see if anybody is against this change, as it could break backwards-compatibility.

**Comment by ikkez** [comment]
Basically I would say yes, but I think it depends on what you are doing in the `onload` event. In case you modify class properties, i.e. in an extended class, those would not be modified anymore when using skip. Maybe factory should call a new `onfactory` event and skip keeps going with `onload`.

**Comment by xfra35** [comment]
> In case you modify class properties, i.e. in an extended class, those would not be modified anymore when using skip

That's smart. I didn't think about that.

Then it definitely belongs to `skip`. And the solution could be to call `skip(0)` at the end of `factory()`. Exactly like `load()` does. What do you think?

**Comment by xfra35** [comment]
Ah no, wait a bit. That won't work since `load()` itself triggers indirectly `factory()`.

**Comment by ikkez** [comment]
reopen if you want to roll it up again ;)
