### ISSUE TITLE
Sync repository with packagist (3.5.1 not available)

### ISSUE THREAD

**Issue by Rayne** [bcosca/fatfree-core#108]
Happy new year,

the [3.5.1](https://github.com/bcosca/fatfree-core/releases/tag/3.5.1) release of `fatfree-core` isn't available on [packagist.org](https://packagist.org/packages/bcosca/fatfree-core). Please sync it.

**Comment by xfra35** [comment]
Looks synced now. I think it's [automatic](https://packagist.org/about) actually:
> New versions of your package are automatically fetched from tags you create in your VCS repository.

**Comment by Rayne** [comment]
You are right. I assume that @bcosca hasn't configured the auto-update (on `push`) hook, so synchronization got delayed. It's also possible to trigger it manually.

**Comment by ikkez** [comment]
Afaik @sn0opy (owner of the packagist entry) had to manually resync the repository, because there is no push-hook configured by the repo owner (bcosca).
