### ISSUE TITLE
Database object returns all variables, whether you can optimize?

### ISSUE THREAD

**Issue by cybrobin** [bcosca/fatfree-core#109]
Database object returns all variables, whether you can optimize?

**Comment by KOTRET** [comment]
please clearify your request - what exactly you mean? The database-object is not just a collection of properties of a record, its an object to work with. So var-dumping it will of course print several internal variables. Possibly `cast()` is your friend.

**Comment by cybrobin** [comment]
Thanks.
Ex.
$db = new DB\SQL($dsn);
$mapper = new DB\SQL\Mapper($db, 'users');

$db->exec($sql); //return an object, 
$mapper->find();  
or 
$mapper->select();  //return an object

Why not return an array?  return an object wether  takes more memory?

**Comment by KOTRET** [comment]
welcome to object-orientation :grin:
DB is an object to exec the underlying queries and return the data. The Mapper-Object in contrast is designed to move through this data and call actions like "delete" or "move next" on the data that is provided by the DB-object: `$record->erase()` will call the corresponding query with the help of $db.
If you need an array-representation of the record, use `$mapper->cast()`.
