### ISSUE TITLE
Overhaul MongoDB code due to possible deprecation of php-mongo 

### ISSUE THREAD

**Issue by sn0opy** [bcosca/fatfree-core#111]
Distributions like Arch Linux have depecreated the php-mongo extension and switched to php-mongodb which is using http://mongodb.github.io/mongo-php-driver/ since the [release of PHP 7](https://www.archlinux.org/news/php-70-packages-released/). 

Unfortunately, beside renaming the module, the whole process to build a connection, perform queries etc has changed as described here: http://mongodb.github.io/mongo-php-driver/commands/

**Comment by AmarettoSlim** [comment]
+1

**Comment by pboese** [comment]
+1

**Comment by zeeshanyshaikh** [comment]
Any update on this?

**Comment by kavin-90** [comment]
i think php-mongo is dead i think it replaced by other monogodb(php-mongodb) package.

**Comment by zeeshanyshaikh** [comment]
Yes, **php-mongo** is dead and fat-free is using same. When can **php-mongodb** support is expected? Thanks.

**Comment by WilliamStam** [comment]
yeah im stuck on this now aswell... any time frames?
