### ISSUE TITLE
Adjust markdown to kramdown

### ISSUE THREAD

**Issue by Fohlen** [bcosca/fatfree-core#113]
You should consider adjusting F3's markdown interpretation to be similar to [kramdown](http://kramdown.gettalong.org/).
Why? GitHub just recently announced that this is the major supported implementation and should therefore be a direction given attention, especially since people here use F3 in the same manner than Jekyll does.

**Comment by sn0opy** [comment]
I don't see any need for this issue actually. If there's anyone willing to implement the kramdown features into the markdown class, a pull request should do the job.
