### ISSUE TITLE
Loading base.php a bit slow, when PSR-7 will support it?

### ISSUE THREAD

**Issue by cybrobin** [bcosca/fatfree-core#114]
Loading base.php a bit slow, when PSR-7 will support it?

**Comment by KOTRET** [comment]
please provide some more informations about this "issue": Are you trying to...
a) say that loading base.php is slow? Any performance-data for this?
b) ask if F3 will support PSR-7? afaik no.

**Comment by sn0opy** [comment]
Going to close this issue, since @cybrobin hasn't been really active on Github this year and hasn't replied to this issue yet anyway.
