### ISSUE TITLE
Markdown parsing problem in F3 web site

### ISSUE THREAD

**Issue by mehmetcoskun** [bcosca/fatfree-core#120]
Hello,

It ma be a slight issue but I wanted to point out anyway in case it may be causing other formatting problems.

Yellow areas in F3 documentation has a markdown parsing problem. They don't get links parsed properly. I am adding the screen shot on the attach here.

![markdown-parsing-problem](https://cloud.githubusercontent.com/assets/13032263/13215374/8868a906-d95d-11e5-819c-47058e26dfe0.png)

Please have a look.

Mehmet.
---

**Comment by xfra35** [comment]
Fixed [here](https://github.com/F3Community/F3com-data/commit/f96bb82b3cf15a782df46690277fa5e892c92037).
Thanks for reporting.
