### ISSUE TITLE
remain PHP 5.3 support for F3 3.5.x

### ISSUE THREAD

**Issue by ikkez** [bcosca/fatfree-core#122]
Since @bcosca has declared PHP 5.4 as the minimum required version of PHP to run fat-free in the latest commits to the dev version, there is no way to get maybe important fixes to bugs that might have occurred in 3.5.1 to your php 5.3.x project. Of course I can honestly understand that step and I am in favor for the php 5.4 base, but since some customers maybe still have old systems and your recently upgraded F3 project now seems to become unpatchable with that 5.4 requirement, I am raising my hand and vote to keep support for php 5.3.x for the current v3.5.x minor version. The way I suggest is:

- [ ] raise current dev baseline from `3.5.2-Dev` to `3.6.0-Dev`
- [ ] checkout `3.5.2-Dev` commit https://github.com/bcosca/fatfree-core/commit/29298fc762f895c2edbd6bfddf21febcf77100d6 into a new *php53* branch
- [ ] cherry pick *only important patches*, possibly rewrite them to keep php5.3 compatibility and merge them into the php53-branch
- [ ] release 3.5.x versions with hotfixes from time to time (maybe until end of 2016)

I think with an active growing F3 developer community, we as the core team has some sort of responsibility. In my opinion this includes to announce such dependency requirement changes, that might look trivial to us, but can lead to big problems in projects where the dev-team rely on common versioning paradigms, where a single patch level should not do such a change.

**Comment by Rayne** [comment]
What's your idea to document new features or feature divergences?

I'm not a big fan of `PHP 5.3`. It's  EOL since August 2014. Even `PHP 5.4` isn't supported by upstream. On the other hand there is `Red Hat 6` which has standard support till November 2020 and it looks like it's still shipping and supporting `PHP 5.3`.

**Comment by ikkez** [comment]
I'm not a big fan of PHP 5.3 too, but I'm just telling that we should keep an eye on proper versioning. And versionable docs should be there regardless of this compatibility branch. As long as this is just about hotfixes, the changelog is the way to go.
