### ISSUE TITLE
XFRAME and application flow

### ISSUE THREAD

**Issue by y-lohse** [bcosca/fatfree-core#128]
Hi,
F3 is currently very opinionated and sends a X-FRAME-OPTIONS header by default. Sadly there seem to be no way to prevent that, which is a problem when you're trying to build a page that is meant to be embeded.

AFAIK, the best we can do is to set it to `ALLOW-FROM *`, which will make the header work on some browsers and be ignored in some others, [like Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=129139). While it works, it still triggers an error log in the client's console.

I'd like to be abble to *not* send the header at all. Alternatively, it'd be nice to be abble to change the value of that header (and any header for that matter, especially CORS stuff) in the `beforeRoute` or something like that, and not just before the call to `run()`.

**Comment by ikkez** [comment]
Hi. So your proposal is to i.e. set the [XFRAME](http://fatfreeframework.com/quick-reference#XFRAME) var to `false`, which should then skip to send the X-Frame-Options header completely, yeah?

**Comment by y-lohse** [comment]
Yep.

It's probably a separate issue, but I also think it would be better to start sending headers *after* the `beforeRoute` hook has been called, or even after the `afterRoute` call.

**Comment by ikkez** [comment]
Ability added. To not send any headers at all, use `header_remove()` in your before/afterrender method. The router usually creates headers for controlling the browser cache behaviour, security settings, status codes, session cookies, content type and more.. so only drop those if you know what that means.

**Comment by y-lohse** [comment]
Awesome, thank you!

**Comment by y-lohse** [comment]
Do you have an ETA for when this commit will land in a version (for use with composer)?

**Comment by Rayne** [comment]
The [commit](https://github.com/bcosca/fatfree-core/commit/c8e0976892705af7dec2811c1e3da3936db9418b) is already available with the `composer` tag [`dev-master`](https://packagist.org/packages/bcosca/fatfree-core#dev-master) and the package `bcosca/fatfree-core`. So it's possible to use the latest changes if you don't want to wait for an official tag or release.

**Comment by y-lohse** [comment]
Ah, good to know, thanks. Is that branch considered stable?

**Comment by ikkez** [comment]
currently yes ;) but next release is coming soon, hopefully..
