### ISSUE TITLE
Composer/Packagist version issues?

### ISSUE THREAD

**Issue by ptdev** [bcosca/fatfree-core#132]
Hi, I was just running into some issues sending emails on some projects which was strange since it seemed to be the same issues I had a few days ago before these latest smtp fixes.
After some testing I came to the conclusion that the issue only happened on the projects that are using composer.

It appears as the version that's available on packagist isn't quite up to date with this repo since running "composer update" or even a fresh install of "dev-master" doesn't download these latest changes that were recently made on the smtp class.

I'm not exactly sure how packagist works from a maintainer's point of view so I'm not really sure if there's something that has to be done to update it or if there's some kind of delay or something?

Thoughts?

**Comment by ikkez** [comment]
I think it's because @sn0opy is the maintainer for the [fatfree-core packagist package](https://packagist.org/packages/bcosca/fatfree-core), so the update hooks are probably not setup on this github repo, because only @bcosca can setup those.

**Comment by ptdev** [comment]
Ah ok, sorry I didn't even bother to check who was maintaining the project on packagist, it's a bit hidden.
I'm hoping @sn0opy will update it soon but ideally @bcosca would setup the update hooks so we can have the latest fixes available on composer as soon as code is committed. Any reason this isn't already happening?

**Comment by ptdev** [comment]
Closing this as it appears that the version on packagist has been updated.
