### ISSUE TITLE
Proposal: elaborate CLI mode

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#134]
Hi,

At the moment, the framework supports a CLI mode which is primarily intended at testing HTTP requests locally: `index.php /home`.

What do you think of broadening this support to make it possible to build human-friendly CLI apps as simply as we build web apps? Would it be out of scope?

I was thinking of:
- combining command-line arguments into a virtual URI. For example, `index.php log show --limit=50` would request `GET /log/show?limit=50`.
- adding a `[cli]` route type to prevent CLI routes from being available online

So writing a command-line maintenance app would be as simple as:

``` ini
[routes]
GET /log/show [cli] = CLI\Log->show
GET /log/clear [cli] = CLI\Log->clear
GET /cache/clear [cli] = CLI\Cache->clear
GET /help [cli] = CLI\Help->index
GET /help/@command [cli] = CLI\Help->@command
```

Command-line options would be stored in the query string and would be of 4 types:
- `-v` => `?v=1`
- `-n=23` => `?n=23`
- `--force` => `?force=1`
- `--grep=foo` => `?grep=foo`

NB: combined single-letter options would be supported.

So for example:
- `index.php help cache --grep=foo` would request `GET /help/cache?grep=foo`
- `index.php cache clear -fvi` would request `GET /cache/clear?f=1&v=1&i=1`

If you're interested in this change, I can submit a PR. This should be a matter of:
- elaborating [this](https://github.com/bcosca/fatfree-core/blob/aa5a9d1941123cc2fff6a815ffaa5004fede2910/base.php#L2048) block of code
- adding support for the `[cli]` route type

**Comment by bcosca** [comment]
Excellent idea. Just that I'm not comfortable (only me probably) with assigning 1 to a value-less argument, boolean seems more intuitive in this case, though we know it evaluates to TRUE anyway.

**Comment by Rayne** [comment]
The proposal mocks `GET` requests, which (normally) only support array and string values. Receiving a boolean could be unexpected. On the other hand it would be a more or less intuitive workaround for optional flag arguments, e.g.:

**Manage users**

```
# Delete user 42
app users --delete 42

# Whoops, deleted user 1!
# I even didn't specify a user!
app users --delete
```

**Optional arguments (none or one argument)**

```
# Clear all caches
app cache --clear

# Clear a specific named cache (e.g. cached sessions, thumbnails, minified files, …)
app cache --clear=sessions
```

**Comment by bcosca** [comment]
IMO, it is the route handler's and not the framework's responsibility to take care of arguments that contain no values. Normally, an HTTP query like `?x&y=2` will translate to `$_GET['x']=NULL` and `$_GET['y']=2`. How and why that `x` is there shouldn't bother the framework at all, so `--x --y=2` should have the same meanings.

**Comment by xfra35** [comment]
Here it is guys.

As suggested by @bcosca, simple flags are given an empty value.

NB: repeated options such as `cmd -e=foo -e=bar` are not directly supported since they lead to `$_GET['e']='bar'`. However, they can indirectly be parsed from the raw query string: `e=foo&e=bar`.

**Comment by eazuka** [comment]
Is this CLI mode from @xfra35 now part of the core?

**Comment by xfra35** [comment]
Yes it is.
