### ISSUE TITLE
Question about mapper "changed" flag

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#145]
I just realized that when updating a mapper, the "changed" flag are not reset, which can lead to unexpected behaviour when running non-idempotent "before/afterupdate" hooks.

See this example:
```php
$mapper->email='foo@test.com';
$mapper->save();// afterupdate: if ($mapper->changed('email')) send email
$mapper->foo='bar';
$mapper->save();// email is sent twice
```

So should we consider this as a bug or as a misusage?

If we consider this is a bug, we should reset the "changed" flags inside `update()`.

**Comment by KOTRET** [comment]
`[x]` bug
`[ ]` feature

saving an entity imho should mark the newly updated / inserted as unchanged

**Comment by bcosca** [comment]
I agree this is a bug

**Comment by ikkez** [comment]
fixed in https://github.com/bcosca/fatfree-core/commit/18ce506100d63ad852da78d877696d95f2e64995
