### ISSUE TITLE
Image->render() signature

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#146]
On the [docs](https://fatfreeframework.com/image#render), we have the following signature:
```php
$img->render( [ string $imageformat = 'png' [, int $quality [, int $filters ]]] );
```

But in [reality](https://github.com/bcosca/fatfree/blob/aba3a54240f3254ce3413f429f826b4e89c508b0/app/image.php#L202), the `render()` method takes the same signature as [imagejpeg](http://php.net/manual/en/function.imagejpeg.php) and [imagepng](http://php.net/manual/en/function.imagepng.php), which means the second argument should either be `NULL` or a string or a stream.

So what do you think guys? Should we fix the docs or fix `render()`?

Fixing the docs is easy but on another hand, that extra second argument is useless as it should always be set to `NULL` since `render()` is meant for output rendering.

The same reflexion applies to `dump()`.

**Comment by ikkez** [comment]
Well as it's not really meant to use that parameter, I think we should patch `render()` and `dump()` accordingly.

**Comment by KOTRET** [comment]
imho the docs need to be fixed, as `Image->render` is just a wrapper for calling `image(jpg|png)`.
Sidenote: looks like imagejpg does not support the filters argument.

**Comment by xfra35** [comment]
Ok thanks guys. Fixed then.
