### ISSUE TITLE
Error  in Magic.php?

### ISSUE THREAD

**Issue by richgoldmd** [bcosca/fatfree-core#147]
I believe I found an error in magic.php.

This code:

```
	function offsetset($key,$val) {
		return Base::instance()->visible($this,$key)?
			($this->key=$val):$this->set($key,$val);
	}

```

Should be:

```
	function offsetset($key,$val) {
		return Base::instance()->visible($this,$key)?
			($this->$key=$val):$this->set($key,$val);
	}
```

The `$ ` before key is missing.

This would only be seen when accessing a true property as an array element, which is unlikely to happen and may be why this hasn't been caught. Unless I'm mistaken...

**Comment by kavin-90** [comment]
I think **$this->key** is correct because $this refer here is F3 so **->key** is data within $this

**$key** is data for passing `$this->set` is F3 set so `$this->key` will be also F3 get Key

Maybe i'm wrong but can't say but i think what i say is correct

**Comment by richgoldmd** [comment]
This is a snippet from the Magic class - so I think $this refers to the instance of Magic - also the corresponding offsetget() method uses

```
$this->$key
```
The reference to Base is just a convenience method for checking if a property exists and is visible (e.g. public), but the object being tested is $this - which is an instance of Magic.

**Comment by xfra35** [comment]
Well spotted! Thanks.
