### ISSUE TITLE
Hive HOST with multiple server_name on nginx

### ISSUE THREAD

**Issue by ptdev** [bcosca/fatfree-core#154]
Hey, not really sure if this is a bug as it's probably by design, but would appreciate a clarification.

When using nginx, one can setup its server_name parameter with multiple domains. I assume this is the same as using both ServerName and ServerAlias on apache.

For example:

`server_name example.com cname.anotherdomain.com etc.domainthree.com;`

In this case, F3 seems to always set the hive HOST variable according to $_SERVER['SERVER_NAME']

Simple test assuming the above setup using "etc.domainthree.com"

```
var_dump($f3->get('HOST'));  // example.com
var_dump($f3->get('SERVER.HTTP_HOST')); // etc.domainthree.com
var_dump($f3->get('SERVER.SERVER_NAME'));  // example.com
```

The hive's HOST var is then used inside the reroute() method. So, when using any other domain, if I call reroute, F3 automatically "redirects" the user back from one of the secondary domains back to the first one. 

Is this correct behavior?
And is there any way to make reroute stick to the domain that's being used? (The variable that seems to have the correct domain inside the hive is at HEADERS.Host and it's also at SERVER.HTTP_HOST instead of SERVER.SERVER_NAME as seen in the above test)

I previously also came across another issue that may be related. When using cookies I also have to set:

`$f3->set('JAR.domain', $f3->get('SERVER.HTTP_HOST'));`

Otherwise the cookies get set with the original domain and not the domain alias being used.

Thanks

**Comment by ikkez** [comment]
You have to fix it in your nginx config. See duplicates for solutions:

https://github.com/bcosca/fatfree/issues/925#issuecomment-214982067
https://github.com/bcosca/fatfree/pull/350
https://github.com/bcosca/fatfree/issues/347
https://github.com/bcosca/fatfree/issues/520

**Comment by ptdev** [comment]
:+1: ikkez

Fixed it by adding the following on my nginx location block as noted in one of those threads:

`fastcgi_param SERVER_NAME $host;`
