### ISSUE TITLE
SMTP multipart message

### ISSUE THREAD

**Issue by ikkez** [bcosca/fatfree-core#161]
The SMTP class was refactored a lot. Since then I'm not able to send multipart messages anymore correctly. What's the desired method to send `text/plain`and `text/html` within one message @bcosca ?
The code I used for `v3.5.1` looks like this (taken from my [mailer](https://github.com/ikkez/F3-Sugar/blob/master-v3/Mailer/mailer.php#L198)):

```php
$body = '';
$hash=uniqid(NULL,TRUE);
$eol="\r\n";
$this->smtp->set('Content-Type', 'multipart/alternative; boundary="'.$hash.'"');
$body .= '--'.$hash.$eol;
$body .= 'Content-Type: text/plain; charset='.$this->charset.$eol;
$body .= $this->message['text'].$eol.$eol;
$body .= '--'.$hash.$eol;
$body .= 'Content-Type: text/html; charset='.$this->charset.$eol;
$body .= $this->message['html'].$eol;
$this->smtp->send($body);
```

the resulting mail appears to be blank at my google mail.

**Comment by bcosca** [comment]
Does it affect Gmail only? Gmail introduced some changes last week. CSS doesn't have to be inlined anymore - at least that's their primary purpose; could be that you might be experiencing a bug there.

**Comment by ikkez** [comment]
No I used a bare-bone example with just some html tags to make text bold, etc.
Maybe it's something with the headers or the boundary hash.. I'm not sure. I can roll back and compare the generated body from 3.5.1 with the current if that is helpful.

**Comment by ikkez** [comment]
I compared the mails and the only difference was a missing $eol in the new mail. added here https://github.com/ikkez/F3-Sugar/commit/5dfbb98d929cbb0acee9c709f055d4206982553c 
problem solved.
