### ISSUE TITLE
 f3->abort connection: close header

### ISSUE THREAD

**Issue by zutto** [bcosca/fatfree-core#162]
The [f3->abort ](https://github.com/bcosca/fatfree-core/blob/master/base.php#L1639) function is missing connection: close header, I have understood that this might be missing intentionally or not.

The good thing about this header is that it closes the TCP connections to the server immediately, but that is also downside which is why it might have been intentionally left out.

So I am opening this issue to verify if this is the case, or if it has simply been forgotten.

-Z

**Comment by xfra35** [comment]
For some reason, it was dropped here: https://github.com/bcosca/fatfree-core/commit/2134fe1f67ba6fc78ae79b35816050acd0da8a06

**Comment by bcosca** [comment]
Don't know how that line got lost in that commit, but it is now restored.
