### ISSUE TITLE
Cache SEED cannot be updated once set

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree-core#164]
Hello,

When using the same SEED on different domains then loading the config file, the SEED value is not being updated in the Cache instance. It was working in the version where `SEED` was added.
We have the following case:
1. We create an `F3` instance.
2. The `SEED` hive key is set to a default hash.
3. We load ìni`configuration that contains a value for`SEED`
4. `SEED` value is updated in the hive but not in the Cache$prefix.

The call stack is the following.

```
.../bcosca/fatfree-core/base.php:353 [Cache->load()]
.../bcosca/fatfree-core/base.php:1841 [call_user_func_array()]
.../app/classes/application/Bootstrap.php:102 [Base->config()]
.../app/classes/application/Bootstrap.php:62 [application\Bootstrap->loadConfiguration()]
/index.php:26 [application\Bootstrap->__construct()]
```

**Comment by ikkez** [comment]
The Cache instance copies the `SEED` upon loading. Fetching it from the Hive all the time could make it slow. Just ensure to initialize the Cache after setting or changing the seed. A simple `CACHE=true` should be enough.

**Comment by ikkez** [comment]
Another idea could be to put a reference here. Does it help when you change this line https://github.com/bcosca/fatfree-core/blob/master/base.php#L2515 to 

```php
$this->prefix=&$fw->ref('SEED');
```
?

**Comment by GhaziTriki** [comment]
I thing putting having a reference of the `SEED` is a good idea as a developer may need to look for keys saved under another seed.

**Comment by ikkez** [comment]
Well, if we put a reference in here, it's maybe updated automatically, if you change `SEED`, but you won't be able to work with 2 Cache instances that uses 2 different SEEDs at the same time. I.e.

```php
$f3->SEED = 'shared-seed-1';
$cache1= new \Cache(true);
$f3->SEED = 'shared-seed-2';
$cache2= new \Cache(true);

$cache1->set('foo','123'); // this will use shared-seed-2 now
$cache2->set('foo','456');
```

I think it's better not to change this. Just initialize (again) your Cache engine after setting the SEED you need.

**Comment by KOTRET** [comment]
why not add a field SEED to the Cache-Class and initialize with Hive->SEED by default and provide an additional (optional) param for a custom seed?

**Comment by ikkez** [comment]
that's actually was we have right now https://github.com/bcosca/fatfree-core/blob/master/base.php#L2586
except the part of overwriting it afterwards without touching the HIVE->SEED, but wouldn't that be too fat?

**Comment by KOTRET** [comment]
Just noticed i woke up sleeping dragons, I'm sorry for commenting this old thread 😀
Well, so a proper workaround is given, the usage just feels a bit strange...

```php
$f3->SEED = 'shared-seed-1';
$cache1= new \Cache(true); // with default-SEED as prefix
$cache2= new \Cache(true, 'shared-seed-2'); // custom prefix
```

**Comment by GhaziTriki** [comment]
@KOTRET thanks for your last comment, we still need that advice for the product which is still running on production 😄
