### ISSUE TITLE
Translation system is buggy when using dots

### ISSUE THREAD

**Issue by nanawel** [bcosca/fatfree-core#165]
Due to the way dots are interpreted when assigning data to F3 hives, it sometimes leads to a buggy behaviour when using them with translatable strings (not only with those, but more generally with all hive keys ending with dots).

**dict/fr.php**
```php
return array(
    'My string'    => 'Ma chaine',
    'My string.'   => 'Ma chaine.',
    'My string...' => 'Ma chaine...'
);
```

**test.php**
```php
$fw = \Base::instance();
echo $fw->get('My string');
```
**EXPECTED RESULT**
```
Ma chaine
```

**ACTUAL RESULT**
```
Ma chaine...
```

Would it be possible to disable at call (or for some hive keys) the "split-on-dots" behaviour? That would really help.

Thanks

**Comment by xfra35** [comment]
I guess the whole hive concept was built with basic alphanumeric keys in mind (`0-9a-z_`). 

Why are you indexing your dictionary with plain strings?

**Comment by ikkez** [comment]
What version are you using? It's not allowed to use a space char in a root hive name. That's will give you an `Invalid hive key` error.

**Comment by nanawel** [comment]
It doesn't seem to be forbidden in the version I'm using (branch dev-master [revision 3ec96809d79a2fca13eb46c62582c9da171af1a3](https://github.com/bcosca/fatfree-core/tree/3ec96809d79a2fca13eb46c62582c9da171af1a3))

I'm using plain strings because it's easier to manage translations than with codes. See this example:
```php
return array(
    'Hi {0}, welcome back to {1}' => 'Bonjour {0}, bienvenue sur {1}'
);
```
Simple and clear isn't it?
Anyway, it's just a possible alternative when dealing with i18n. It worked perfectly fine so far, except for this very case.

**Comment by nanawel** [comment]
@ikkez I'm not in a root hive as i'm using the PREFIX config key (my example might a bit over-simplified I admit).

**Comment by ikkez** [comment]
The dot is an array separator, and your lang keys will fall apart when you'll ever put a dot or object access (`foo->bar`) in the keys. I recommend using abstracted language keys like `'user_welcome' => 'Hi {0}, welcome back to {1}'`

**Comment by nanawel** [comment]
Thanks, recommendation noted, but I can't apply it at this point.
Should I understand that introducing a new way to handle the dots in hive keys is excluded?

**Comment by xfra35** [comment]
Wait a bit guys... @bcosca has more than one trick up his sleeve. See:

```php
$f3->set('DICT[foo .bar]','baz'); // or $f3->set('DICT["foo .bar"]','baz');
echo $f3->get('DICT[foo .bar]'); // baz
```

I didn't know this one ^^

So maybe it'll help you finding a way out @nanawel.

**Comment by xfra35** [comment]
So if you change your dictionary file into:

```php
return array(
    '[My string]'    => 'Ma chaine',
    '[My string.]'   => 'Ma chaine.',
    '[My string...]' => 'Ma chaine...'
);
```
and providing you're using `PREFIX = DICT.`, you'll be able to call:

```php
echo $f3->get('DICT[My string.]'); // Ma chaine.
```

Extreme coding ^^

That's probably not what you've been expecting but it works.

**Comment by ikkez** [comment]
@xfra35 great investigation ;)

**Comment by nanawel** [comment]
That's a clever trick! But unfortunately I don't think I'll be able to use it :(
Thanks anyway for your help!

**Comment by xfra35** [comment]
I guess you don't want to rewrite all your dictionary files. But there must be a way to do that automatically.

For example, you could replace:

```php
$f3->LOCALES='/path/to/dict/';
```

by this:

```php
$lex=[];
foreach($f3->lexicon('/path/to/dict/') as $k=>$v)
  $lex["[$k]"]=$v;
$f3->mset($lex,$f3->PREFIX);
```

(providing your dictionary files don't hold nested arrays, otherwise you'll need recursion)

**Comment by nanawel** [comment]
Not a pretty solution but anyway: I managed to get what I wanted by encoding (b64) the keys before returning the array in the dict file, and then decoding the keys when accessing them. That way I'm sure I'll get no dots in the keys.

As I already had a dedicated I18n wrapper class around `\Base`, it was quite easy and clean to do it.

Thanks anyway for your help guys.
