### ISSUE TITLE
Cannot remove cached value on memcache backend

### ISSUE THREAD

**Issue by dfumagalli** [bcosca/fatfree-core#170]
Hello,

[I have reported this issue](https://groups.google.com/d/msg/f3-framework/t0hYxPVuFeE/9cwu8RcZAwAJ) on the Google forum, but since it could be a bug I am reporting it here as well.

Basically, I am using F3 3.6-dev (downloaded yesterday) on a vanilla Ubuntu 14.04.5 LTS VPS + Apache 2.4.7 + PHP 5.5.9 + memcached 1.4.14 that comes with it.

When I cache a SQL query result with the F3's Cache object as follows:

`$result = $db->exec($sql, null, [7200, 'customCacheTag']);`

I have been told by @ikkez to use this syntax to force remove it from memcache:

`Cache::instance()->reset('customCacheTag');`

When I do that, F3 goes into the proper function and memcache management code. However for some reason the cache key=>value timestamp is checked against time() and that comparison always fails because it's set to a value greater than what time() returns. I have run a sample cache reset call with XDebug and have taken a screenshot of the values the various variables and if() clauses values.

Here's the involved F3 code, from base.php:

![2016-11-15 23_11_22-fatfree-core-editor](https://cloud.githubusercontent.com/assets/5745561/20348304/adff8050-abfc-11e6-9382-d3c6824595c9.png)

Here's the screenshot of the various variables:
![2016-11-15 23_07_21-fatfree-core-watches](https://cloud.githubusercontent.com/assets/5745561/20348355/efaea1a2-abfc-11e6-94d4-78b74713f493.png)

As you can see, most code works as expected. $data gets the appropriate value ('nlo_car_plate_codes' cache tag in this example) and the preg_match() returns 1.
However as you can see in the screenshot, `$val[1]+$lifetime<time()` comparison always fails, because 
`$val[1]+$lifetime` is > `time()`. $lifetime is set to zero, so there's something unexpected with `$val[1]`.

Full details and additional use cases and code are provided in the F3 Google forum thread I linked at the top of this post.

Thanks in advance,
Dario Fumagalli

**Comment by ikkez** [comment]
Well the cache reset method compares the expire time. `var_dump("1479254498"+0<time());` is true here, so there should not be a problem. The conclusion to force the cache key to be resetted is to add a very low `$lifetime`. 

This should fix it:
```php
Cache::instance()->reset('customCacheTag', -time());
```

**Comment by dfumagalli** [comment]
Hello,

in the screenshot I have sent, there's time() output as well:
```

$val[1] = 1479254498
$time() = 1479251020

```
The whole statement said "false" on my debugger. As a double check, here is the PHP output of the comparison I have just checked again:

![2016-11-16 16_39_33-php_sandbox](https://cloud.githubusercontent.com/assets/5745561/20356203/af1aae78-ac1b-11e6-986e-61d6212c1733.png)

About the negative -time().... to me it looks like a workaround, which is perfect to fix my app right now.

However I am curious about $val[1].
Apparently it's value should be equal to the cache key=>value creation time, instead somehow it's set to creation time + expire time. It's not easily seen here, because the expire time I used (7200) was halfway through when I ran my tests, hence the < 7200 difference.

By the way, a month ago I did a similar test on another memcache function (I think it was "clear()") and that one, too, exhibited the same behavior.

**Comment by ikkez** [comment]
For me this looks like expected behaviour. Nothing to fix here. That's the reason why it's called `$lifetime`, because you could increase or decrease this value upon clearing the cache. So it's a feature, not a bug IMO. All other build-in cache engine clear mechanics seem to work the same. 
If you want to invalidate a cache entry that was created recently and is not expired yet, you need to decrease its expire time with `$lifetime`. So `-time()` should be absolutely valid.

The thing about `cachedump` is a good hint, but this is another issue.

**Comment by dfumagalli** [comment]
That's ok, then I am going to assume the example you gave on the F3 forum should read:

`Cache::instance()->reset('customCacheTag', -time());`

instead of:

`Cache::instance()->reset('customCacheTag');`

Anyway, I don't exactly get the use case for a "`clear()`" and "`reset()`" methods that don't just do the clearing functionality, but also condition it's execution to a `$lifetime`.

**Comment by ikkez** [comment]
Yes I see the problem. Indeed, that's a little bit odd. Maybe we should only check this condition when a `$lifetime` was given? So it becomes:

```php
($lifetime && ($val[1]+$lifetime<time()))
```
@xfra35 @bcosca

**Comment by xfra35** [comment]
I could reproduce the problem. This is related to Memcache because in [this line](https://github.com/bcosca/fatfree-core/blob/5c20d4c712cd9cba72a6918c0e4daebf3640c657/base.php#L2513), we have the following `$data`:
```php
[
  'xxxx.customCacheTag.sql' => [
    354, // data size
    1479402455 // expiration date
  ]
]
```
while the code is expecting to fetch the cached data.

**Comment by xfra35** [comment]
Should be fixed now. @dfumagalli can you test it?

**Comment by ikkez** [comment]
Are you sure? I think the expiration date in the meta $data array looks already good. And from @dfumagalli  explaination it seems like it's already the correct $ttl value. Fetching the actual cache data with memcache_get will return the serialized data. 
maybe its only an issue of proper method description. To me it seems that Cache->reset is actually a method to clean-up the cache (remove expired keys) instead of dropping all entries. This drop line can be moved by $lifetime to define an offset for each entries expiration time.

**Comment by xfra35** [comment]
> I think the expiration date in the meta $data array looks already good

Precisely it should not return the expiration date but the date of storage.

And since `memcache_get_extended_stats` returns an array which consists of `[data size, expiration date]` (instead of `[data, storage date, ttl]`), `$val[1]` didn't throw any error but returned the wrong date instead.

**Comment by xfra35** [comment]
The unserialization was missing... fixed.

@ikkez we could have initially fixed that issue by replacing `$val[1]+$lifetime<time()` with `$val[1]<time()` but that would not have been working for `$lifetime` values other than 0. So we need the initial storage date (not the expiration one), and the only way to get it is to retrieve the cached data.

**Comment by ikkez** [comment]
ahh I see, yes this makes much more sense now.

**Comment by dfumagalli** [comment]
Hello and thank you!

at the moment I am very busy, hopefully I'll be able to test the new changes tomorrow or on Monday.

**Comment by dfumagalli** [comment]
Hello again,

Please @ikkez remove the "invalid" label 👍 

@xfra35 I have tested your modification and it works for me.

## Test conditions
**First phase**
_Null hypothesis_ to make 100% sure of results reliability:
- Memcached as cache backend
- Pre-bugfix F3 framework
- Basic controller that routes to this code:

```
public function cacheTagReset($f3, $params)
    {
        // Only do something if debug is on
        if ($f3->get('DEBUG') > 0) {
            if (isset($params) && !empty($params)) {
                // Avoid XSS with clean()
                $cacheTagName = (isset($params['cacheTagName']) ? $f3->clean($params['cacheTagName']) : false);

                if (false !== $cacheTagName && !empty($cacheTagName)) {
                    \Cache::instance()->reset($cacheTagName);
                    echo "Cache key $cacheTagName has been cleared\n";
                }
            }
        }
    }
```

As you can see I have purposedly removed the `-time()` workaround by @ikkez from the cache `reset()` call.

I have run some controllers invoking models that in turn create sophisticated cache tags, including hashing some portions of themselves:

![2016-11-19 17_03_38-cache](https://cloud.githubusercontent.com/assets/5745561/20457042/6924e6f2-ae7a-11e6-8793-e68d12a66182.png)

Calling the `cacheTagReset()` function (passing the cache tag names one by one as parameters) did **not** clear the cache tags. Bug is thus confirmed for pre-bugfix code base.

**Second phase**
- I have downloaded and installed a very fresh F3 core: v. 3.6.1 base.php which includes the bugfix.
- I have re-run `cacheTagReset()` passing the cache tag names one by one as parameters.

This time, **it did** clear the cache tags.

Conclusion: _the bugfix works!_

**Comment by ikkez** [comment]
great. thanks for taking the time for testing.
