### ISSUE TITLE
Route tokens passed to action handlers buggy with 3.6.x?

### ISSUE THREAD

**Issue by nanawel** [bcosca/fatfree-core#172]
Hi,
There's a major difference between 3.5.x and 3.6.x on the way route tokens are passed to action handlers.

With the following route definition:
```
GET /mycontroller/@action/*=MyController->@action
```
And the following controller:
```php
class MyController {
    public function myaction($fw, $args) {
        var_dump($args);
    }
}
```
Using this URL: http://www.example.com/mycontroller/myaction/somevar/somevalue
it gives with 3.5.1
```
array(4) {
  [0] =>
  string(40) "/mycontroller/myaction/somevar/somevalue"
  'action' =>
  string(8) "myaction"
  [1] =>
  string(8) "myaction"
  [2] =>
  string(17) "somevar/somevalue"
}
```
and with 3.6.0
```
array(3) {
  [0] =>
  string(40) "/mycontroller/myaction/somevar/somevalue"
  '*' =>
  string(17) "somevar/somevalue"
  'action' =>
  string(8) "myaction"
}
```

Does it look like a bug or is it the normal behavior now? Should'nt the documentation be updated accordingly if so?
(btw I'm referring to https://fatfreeframework.com/base#Wildcards)

**Comment by ikkez** [comment]
This is expected behaviour and was stated in the [release notes](http://slides.com/ikkez/fat-free-v3-6).
The updates to the API documentation are still pending.

**Comment by nanawel** [comment]
Alright, thanks for the information. Nice release notes btw :)
