### ISSUE TITLE
Possible API incompalibity in 3.6.x

### ISSUE THREAD

**Issue by squarerootfury** [bcosca/fatfree-core#173]
I'm not sure if this is maybe connected to #172 

I'm facing the problem that the Middleware from https://github.com/ikkez/F3-Sugar/tree/master-v3/Middleware (which is not the reason of this issue) stopped working on 3.6.0, while it was working on 3.5.1. I know that the code of this 3rd party lib was patched the last time a year ago but it was working quite well until I updated my f3 (using composer).

```
$f3 = Base::instance();
\Middleware::instance()->before(array(
 "GET /start"
), function (\Base $f3) {
    return false;
});
$f3->route("GET /start",function($f3){
    echo "executed"; 
});
if (\Middleware::instance()->run()) {
    $f3->run();
}else{
  echo "Nope";
}
```

This code will always print **executed** instead of the expected **Nope**. The PHP Version is `7.0.13-1~dotdeb+8.1`  on Debian Jessie. The code runs fine on a via composer installed version 3.5.1 of f3.

Are they any planned changes to the API which could explain this problem?

//Edit: Title Update

**Comment by ikkez** [comment]
Probably a bug in the Middleware plugin. The routing has changes slightly, due to cli integration. That's missing in the middleware. I'll have a look at it.

**Comment by ikkez** [comment]
updated [middleware](https://github.com/ikkez/F3-Sugar/tree/master-v3/Middleware). Should be fixed now. No F3 issue.

**Comment by squarerootfury** [comment]
Thank you very much for the fast response and update!
