### ISSUE TITLE
OAuth2 not included in API Reference

### ISSUE THREAD

**Issue by libregeek** [bcosca/fatfree-core#175]
OAuth2 documentation is not available in API reference for v3.6  https://fatfreeframework.com/3.6/api-reference

**Comment by ikkez** [comment]
fixed in https://github.com/bcosca/fatfree-core/commit/945f8bfe81bbd3f40dc2e731cc2902c9c55b4c33

**Comment by martinellipsis** [comment]
thumbsup.

**Comment by richardeth** [comment]
Can someone please private some details, explanation or example?

**Comment by n0nag0n** [comment]
@ikkez I think I fixed part of this when I fleshed out the docs better for 3.7. You could probably close this.
