### ISSUE TITLE
Fulltext Search and filter based on score

### ISSUE THREAD

**Issue by anned20** [bcosca/fatfree-core#179]
I would like to filter on documents that have, let's say, a score from above 1. This is currently not possible.

Using the F3-Sugar/pagination for pagination.

Also saw this: http://stackoverflow.com/questions/29235012/full-text-search-filter-on-text-score

**Comment by xfra35** [comment]
It should be possible. Read this: http://stackoverflow.com/questions/40072333/full-text-search-and-score-sorting-mongodb/40215402#40215402

**Comment by anned20** [comment]
I asked that question myself :-p

The sorting itself goes well based on the field textScore. I want to filter on that: 'car' should match 'car' with a score of 1. I want the results when the score is above ~0.7

**Comment by ikkez** [comment]
I think you can add a finalize or reduce function to the `$options` array to let mongo sort out anything below 0.7 in the final results, or even write your own "scoring" function: https://fatfreeframework.com/3.6/mongo-mapper#$option

not tested, but you get the idea:
```php
$fields=['score'=>['$meta'=>'textScore']];
$mapper=new DB\Mongo\Mapper($db,'mycollection',$fields);
$result = $mapper->find(
		['$text'=>['$search'=>'search text']]
		,[
			'group' =>[
				'keys' => [],
				'finalize' => 
					"function (key, reduced) {
						if (reduced.score > 0.7){
							return reduced;
						}
						return null;
					}",
				"initial" => [],
				"reduce" => 'function (obj, prev) {}'

			],
			'order'=>['score'=>['$meta'=>'textScore']]		
		]
);
```

**Comment by anned20** [comment]
@ikkez Thanks! I got it to work, but I am not getting any results sadly. This is what I have come up with: 
$filter['$text'] = ['$search' => '"'.$searchTerms.'"'];
$options = ['order' => ['created_at' => -1],
   'group' => [
      'keys' => [],
      'initial' => (object) [],
      'reduce' => "function (obj) {
             if (obj.score > 0.7) {
                    return obj;
             }
             return null;
        }",
        'finalize' => ''
    ]
];
`
