### ISSUE TITLE
type is lost on multiple reroute

### ISSUE THREAD

**Issue by Mindiell** [bcosca/fatfree-core#183]
When mocking a request, f3 use its internal "mock" method.
If the result ends with some "rerouting", then the internal "reroute" method is used.
The "reroute" method ends with :
```php
	if (!$this->hive['CLI']) {
		header('Location: '.$url);
		$this->status($permanent?301:302);
		die;
	}
	$this->mock('GET '.$url);
```

which is quite good on the internet but is a problem during tests. Since tests are often done in CLI mode, headers should not be set and a mock should be done which seems ok here.

BUT :
the "mock" method ends up with :
```php
	$this->hive['CLI']=isset($parts[5]) &&
		preg_match('/cli/i',$parts[5]);
```

which sets the "CLI" key-value in f3, thus, after a reroute done with a '[cli]' type, the type is lost and if the second mock ends up again on a reroute, this time the reroute will be done out of CLI mode...

So, while mocking a request, a double "reroute" ends nowhere...

The best option could be to modify the mock call from reroute function like this :
```php
	$this->mock('GET '.$url.($this->hive['CLI']?' [cli]':$this->hive['AJAX']?' [ajax]':''));
```

in order to keep types...

**Comment by xfra35** [comment]
Done. Thanks for reporting.

**Comment by Mindiell** [comment]
Hmm, apparently you used hard type ' [cli]' in the mock request. The other types are never used through "mock" ?

**Comment by xfra35** [comment]
No because of the [conditional loop](https://github.com/bcosca/fatfree-core/blob/342703763d03f20b1e4f215a852262e69939f75f/base.php#L1384) just before.
