### ISSUE TITLE
ROOT System Variable doesn't really give you the right path.

### ISSUE THREAD

**Issue by chez14** [bcosca/fatfree-core#186]
This issue are currently  happens for cross-platform developing.

i've been working on windows and this script are working properly. But when i deploy it into hosting server, it's becaming a bug.

My hosting provider has a linux based server, and the `ROOT` system var didn't give a right path. it didn't start with `/` so it's the real problem when i try to make folder...

Thank you.

**Comment by ikkez** [comment]
I cannot reproduce this. Which F3 version are you using, is this apache or nginx, which version? And what is `$_SERVER['DOCUMENT_ROOT']`? (dump this before including F3)

**Comment by phm3** [comment]
I have the same issue. Using nginx on centos

`$_SERVER['DOCUMENT_ROOT'] = var/www/html`

`$f3->reroute('/any')` never gets me the right path, instead: `/_app/any`

**Comment by onlyongunz** [comment]
@phm3 It seems like our problem are quite different... yet it seems like mistake on `.htaccess` file...

Anyway i'm gonna make a reproduce steps... hang on, still got some tasks to finish T.T

**Comment by kavin-90** [comment]
@phm3 its because you have wrong nginx config i'm using nginx past 2 years it never give me wrong path 😂 

you can use any nginx of cms it will work because all cms , framework nginx config is same

**Comment by phm3** [comment]
> you can use any nginx of cms it will work because all cms , framework nginx config is same

I don't agree with that, but i understand it is your experience with nginx.

**Comment by chez14** [comment]
Agree, not all framework's nginx's config is the same.
Since all framework has their own behavior, I'm pretty much sure that not all framework has the same configuration.

**Comment by kavin-90** [comment]
I checked few mostly framework nginx config/cms they use same config i.e main part

**Comment by dexwerx** [comment]
MS though DOCUMENT_ROOT was a security issue in later versions of IIS, so they keep it blank. 
workaround is to patch it before loading f3.

```
$_SERVER['DOCUMENT_ROOT'] = dirname(__FILE__);  // patch for php 5.3 on IIS6 / DOCUMENT_ROOT is blank!
$fw = require('lib/base.php');                  // load framework
```

**Comment by chez14** [comment]
I'm going to close this issue as i can't reproduce this on newer version. If you feel the problem still persists, please create a new issue.

Thank you.
