### ISSUE TITLE
mcrypt_*() functions are deprecated in 7.1

### ISSUE THREAD

**Issue by nanawel** [bcosca/fatfree-core#187]
Even if the official documentation doesn't say so yet, `mcrypt_*()` functions are deprecated and throw a warning on recent PHP installations (>= 7.1). F3's `Bcrypt` class currently uses `mcrypt_create_iv()` in the `hash()` method.

See https://wiki.php.net/rfc/mcrypt-viking-funeral

`openssl_random_pseudo_bytes()` should be prefered as the only robust solution (and not as a fallback as it is now).

**Comment by sn0opy** [comment]
Well, actually the bcrypt class only exists because people didn’t move to password_hash() and password_verify() yet. Imho it’s finally time to get rid of it.

**Comment by ikkez** [comment]
Yes the bcrypt class was already marked as deprecated and will be dropped in a future release when we raise the minimum php version to 5.5.

**Comment by nanawel** [comment]
Is dropping this class a good solution? In my opinion, it can still be a valid wrapper for crypt/hash functions.

**Comment by bcosca** [comment]
`mcrypt_create_iv` will be used only if the PHP extension is loaded - so this shouldn't be much of a problem with 7.1 users who we expect will not add this to their base installation. This is a non-issue.
