### ISSUE TITLE
Add an option parameter for Cursor->count()

### ISSUE THREAD

**Issue by Kallys** [bcosca/fatfree-core#192]
Hi!

I realize that Cursor->count() function doesn't take an option parameter.
However, sometimes, a "GROUP BY" option (mysql) can be provided and may change the total count value.
This lead to Cursor->paginate() returning a wrong total value, although paginate() function uses the option parameter (when using a "GROUP BY" condition).

Thanks!

**Comment by bcosca** [comment]
Sounds reasonable.

**Comment by Kallys** [comment]
Thanks for your reactivity !

I also did a patch like yours, but it appears that, with a GROUP BY condition, COUNT() will apply to grouped rows...

I found out that the easiest way to perform a right SQL request for paginate() is something like this :
```SELECT COUNT(*) as `rows` FROM (SELECT * FROM `my_table` GROUP BY `group_field`) as tmp```

Instead of :
```SELECT COUNT(*) as `rows` FROM `my_table` GROUP BY `group_field` ```
