### ISSUE TITLE
Web::minify is_bool(strpos($save, '../'))

### ISSUE THREAD

**Issue by bigsiter** [bcosca/fatfree-core#199]
I've updated core from 3.5.1 to 3.6.0 and get the problem with css/js assets.
Inspecting code of Web::minify I have found that check of 
591 : . . . . . . .  is_bool(strpos($save,'../')) &&
does not work for my code: \Web::instance()->minify($file);

If I change it to "!is_bool(strpos($save,'../'))" everything becomes fine.
I am not sure is it right to do so or not...

P.S. Sorry, for my English :)

**Comment by ikkez** [comment]
The code is correct. It's not allowed to move upwards in the file path. Please fix this in your application (i.e. by setting a correct `$path` parameter or `UI` setting).
