### ISSUE TITLE
smtp context error

### ISSUE THREAD

**Issue by ptdev** [bcosca/fatfree-core#200]
Hi, I've recently started getting a 500 when trying to send e-mail.

Here's the code that throws an error:

```
$mail = new \SMTP();
$mail->set('Content-Type','text/html; charset="UTF-8"');
$mail->set('From','"source" <somebody@example.com>');
$mail->set('Subject','subject');
$mail->set('To','"dest" <something@example.com>');
$mail->send('testing');
```

The error is the following:

```
HTTP 500 (GET /test)

[vendor/bcosca/fatfree-core/smtp.php:201] Base->error()
[app/controllers/home.php:153] SMTP->send()
[vendor/bcosca/fatfree-core/base.php:1782] Controllers\Home->test()
[vendor/bcosca/fatfree-core/base.php:1604] Base->call()
[index.php:40] Base->run()
```

If I remove the @ from stream_socket_client around line 197 I get the following message:

`stream_socket_client() expects parameter 6 to be resource, null given`

Any ideas? Thanks

EDIT: works fine with 3.6

**Comment by finoso** [comment]
By default the SMTP class connects to `localhost:25` without any authentication or any other settings. Is that even possible on that host? Did you check your mail server logs?

**Comment by sn0opy** [comment]
By default the SMTP class connects to `localhost:25` without using any authentication etc. Are you sure you're allowed to connect to your local mail server without authentication? Did you check your mail server logs already?

**Comment by ptdev** [comment]
Hi @sn0opy,
Yeah I know it defaults to localhost and my mailserver works fine, but F3 throws the 500 error defined on line 201 before even hiting the mailserver.

Changing to 3.6 stable clears the error. Unfortunately, 3.6 still wasn't updated to include php7+ compatible mongodb drivers so I have to stick with dev-master on composer :(

**Comment by sn0opy** [comment]
Someone else may have a better solution, but just switch to dev-master again, and remove `,$this->context` in smtp.php#L199 for now and see if that fixes your problem.

I recommend you update to latest and just use an alternative like mongodb/mongodb. I've upgraded an old F3 map to 3.6 with that lib which took me <2h and everything runs fine again. The syntax is even the same for most parts.

**Comment by ptdev** [comment]
F3 at dev-master still requires mongodb/mongodb to be installed on php7+. The changes are mostly to be able to use F3's existing mongo wrappers.

As for changing the code, sure, I can also just replace the smtp class with the one from 3.6 and it  should work fine, but I would really just rather use an unmodified version so I can use composer to manage it and not have to remember that I changed file x or y.

But anyway, since the smtp class was working ok until about 2 or 3 commits ago I just opened the issue to let you guys know about it.

I did take a look at the smtp class code, but couldn't figure out what or why exactly that $context/$ctx properties are there in the first place.
AFAIK, they're always null unless we specifically pass a value on the constructor. It's also not described on the phpdoc block.

**Comment by sn0opy** [comment]
Right now there's no ETA or even anyone working on an up to date MongoDB class to utilize the new driver. So I assume you have to stick to the old F3 version for a "bit" longer then.

> I did take a look at the smtp class code, but couldn't figure out what or why exactly that $context/$ctx properties are there in the first place.
AFAIK, they're always null unless we specifically pass a value on the constructor. It's also not described on the phpdoc block.

That's why I recommended to remove `$this->context` to see whether it fixes the issue. Since the default value for it is actuall `NULL` it shouldn't cause an issue. I must admit, I have no idea what else could be used as an "empty" resource. Only option in my head: check if it's set to something else but `null` and use the function without the 6th parameter which sounds pretty dirty actually.

**Comment by ptdev** [comment]
> So I assume you have to stick to the old F3 version for a "bit" longer then.

Sure, but we can't actually use v3.6 when using php7 and mongo together until the changes made on #177 are merged into stable.
That's why I'm using dev-master from f3-core and got the non-working smtp class after running a composer update.

**Comment by ikkez** [comment]
confirmed. same issue here on dev-master

**Comment by KOTRET** [comment]
@ikkez: although closed: why you explicitly lowercase the hostname? Could casing make a difference here?
@bcosca: while reviewing ikkez' commit i wondered why the `EHLO` uses `$fw->get('HOST')` instead of `$this->host`. This needs a fix too?

**Comment by sn0opy** [comment]
> @ikkez: although closed: why you explicitly lowercase the hostname? Could casing make a difference here?
No. Never.

**Comment by ikkez** [comment]
I just wondered what the purpose of `strtolower($this->scheme=strtolower($scheme))` might be and thought that the original intention probably was to apply this on the whole string... it doesn't make a difference though.
