### ISSUE TITLE
Empty PATH system variable when URI path has multiple leading slashes

### ISSUE THREAD

**Issue by Rayne** [bcosca/fatfree-core#203]
The system variable `PATH` is empty when the URI path has multiple leading slashes. The `PARAMS` variable contains the URI path. Tested with …

* `fatfree-core` b11c03eb9903aada164d729f0a2a5ab3363d2d26 (`>=3.6.0`)
* PHP 7.0.
* PHP's built-in HTTP server
* Routes `GET *`, `GET /*`, `GET //*` and `GET //foo`

Case|Value
---|---
URI path | `//foo`
`PARAMS[0]` (Routes `*`, `/*`, `//*` and `//foo`) | `//foo`
`PATH` (Expected) | `//foo` (or `/foo`)
`PATH` (Actual) | Empty string

**Comment by ikkez** [comment]
I'm wondering if `//foo` is a valid route at all.

**Comment by KOTRET** [comment]
@ikkez it is:
http://webmasters.stackexchange.com/questions/8354/what-does-the-double-slash-mean-in-urls/8381#8381
http://stackoverflow.com/questions/20523318/is-a-url-with-in-the-path-section-valid

**Comment by ikkez** [comment]
Problems solved. Issue was that `parse_url()` treats `//foo` as a scheme-less HOST name instead of the actual path when parsing the url. Since `$_SERVER['REQUEST_URI']` can be a relative or absolute URI, the usage of `parse_url` is totally valid,.. just this little edge case didn't came up yet.

**Comment by ikkez** [comment]
Now we can even put some ascii fish in our routes:
`http://f3.int/<°///><`

```php
$f3->route('GET /<°///><',function( Base $f3, $params) {
	var_dump('fish');
});
```
