### ISSUE TITLE
Preview->resolve() array issue

### ISSUE THREAD

**Issue by Seether85** [bcosca/fatfree-core#205]
Hello,

I noticed this morning after updating to F3 3.6.1 that several of my templates including array variables were broken. I don't know if it's me misusing templates or anything, still you can spot the different behaviours between F3 3.6.0 and 3.6.1 by running this simple snippet under the different versions:

	$template = new Template;
	$template_model = '<repeat group="{{ @item_array }}" value="{{ @item }}">
				{{ @item.id }} - {{ @item.name }}
			   </repeat>';

	$item_array = array(
		array(
			'id' => 0,
			'name' => 'Foo'
		),
		array(
			'id' => 1,
			'name' => 'Bar'
		)
	);

	$f3->set('item_array', $item_array);

	$populated_template = $template->resolve(
		$template->parse($template_model)
	);

	var_dump($populated_template);

Results:
**F3 v3.6.0**: _string(140) " 0 - Foo 1 - Bar "_
**F3 v3.6.1**: _string(5) "Array"_

**Comment by ikkez** [comment]
tricky one, but should be fixed now.

**Comment by ikkez** [comment]
That was always the case. The templates compiles to:

```php
[usercfg]
var1 = <?= $var1 ?>
var2 = <?= $var2 ?>
```

but in PHP, when the file is required, the new line after `?>` is consumed. Usually this is no problem, and for rendering config files, there is the _$f3->config('test.ini',_ **TRUE** _);_ option. I think we maybe could patch this odd behaviour though.

**Comment by ptdev** [comment]
Was it always the case? I'm only getting this behavior now and not before and the only thing I've changed was updating F3 to try out 3.6.1.
Trying with an an older version (for example 3.5.1) makes it work as expected again and writes the ini file in the correct format with the linebreaks. (at least on my setup, but please confirm this also happens on your setup if you have the time)

**Comment by ikkez** [comment]
Okay I tested it with 3.6 once and had the same (not working) result. I tested once more now and noticed that I was holding it wrong (had CRLF line breaks on the ini file), changed that and now I see that it was working on 3.6 indeed.. gimme a second.

**Comment by ikkez** [comment]
@ptdev can you check if the patch is working for you? Looks good here.

**Comment by ptdev** [comment]
@ikkez Seems to be working as expected now.

Thanks for the fix. 👍

**Comment by SylwesterZarebski** [comment]
This fix broke expressions in {{ }} templates and bring problems with tags like TEXTAREA, which have now added artificial EOL at end, when should not.
See issue https://github.com/bcosca/fatfree/issues/1048
