### ISSUE TITLE
DB classes (SQL, Mongo, Jig) as Singletons

### ISSUE THREAD

**Issue by pgrzego** [bcosca/fatfree-core#207]
Like Base class, in my opinion DB classes should also have only one concrete object initiated at a runtime. Thus it would be great for them to extend the Prefab class like Base does.

In my particular case I want to automate dependency injection so I won't have to care about dependencies when I create my objects. But with current architecture I will have a separate DB object for each data mapper :(

**Comment by Rayne** [comment]
The change request prevents simultaneous database connections, e.g. to two MySQL servers at the same time. The DI should be able to resolve dependencies without this change.

1. Register your shared DB object
2. Let the DI inject the DB object whenever necessary

My read is that you would like to use a static method to get a fixed DB object. This would be similar to service location. If this is what you are aiming for, then have a look at the [`Registry`](https://fatfreeframework.com/3.6/prefab-registry#Registry) class.
