### ISSUE TITLE
fatfreeframework with SQL Server databse using mapper copyfrom method with partial insert

### ISSUE THREAD

**Issue by josephcrawley** [bcosca/fatfree-core#210]
I am attempting to insert a record using the `copyFrom('POST')` and `save()` methods of fatfreeframework v3.5. The data from `POST` does not contain an `id` field which for this table is set as an autoincrement. The SQL from the logs is

```sql
SET IDENTITY_INSERT [xrefs] ON;
INSERT INTO [xrefs] ([status], [supply_id], [description], [unit], [unitcost], [cap], [rev], [buq])
VALUES ('test', 'Htest', 'test', 'test', '1', '1', 1, 1)
```

As you can see fatfree is adding the set identity insert despite the fact there is no id column included in the insert. Is there a way to tell mapper not to set this flag? Or is there another workaround? I could get the current max ID and then insert +1 but that seems clunky.

I should add this SQL fails because the id column is not included in the columns list.

```
    $this->db->exec(
            (preg_match('/mssql|dblib|sqlsrv/',$this->engine) &&
            array_intersect(array_keys($pkeys),$ckeys)?
                'SET IDENTITY_INSERT '.$this->table.' ON;':'').
            'INSERT INTO '.$this->table.' ('.$fields.') '.
            'VALUES ('.$values.')',$args
        );
```

This is the code that sets IDENTITY_INSERT in mapper.php function insert.

```
    $this->logger->write( 'xrefs schema:'. 
    json_encode( $this->tongpodb->schema( 'xrefs' ) ) );
```

Calling schema on the the db object gives back this array

```
{
"id":{"type":"int","pdo_type":1,"default":null,"nullable":false,"pkey":true},
"changed_date":{"type":"datetime","pdo_type":2,"default":null,"nullable":true,"pkey":false},
"status":{"type":"varchar","pdo_type":2,"default":null,"nullable":false,"pkey":false},
"supply_id":{"type":"varchar","pdo_type":2,"default":null,"nullable":false,"pkey":true},
"description":{"type":"varchar","pdo_type":2,"default":null,"nullable":true,"pkey":false},
"unit":{"type":"varchar","pdo_type":2,"default":null,"nullable":false,"pkey":false},
"hcpcs":{"type":"char","pdo_type":2,"default":null,"nullable":true,"pkey":false},
"unitcost":{"type":"decimal","pdo_type":2,"default":null,"nullable":false,"pkey":false},
"cap":{"type":"decimal","pdo_type":2,"default":null,"nullable":false,"pkey":false},
"rev":{"type":"smallint","pdo_type":1,"default":null,"nullable":false,"pkey":false},
"buq":{"type":"smallint","pdo_type":1,"default":null,"nullable":true,"pkey":false},
"create_ts":{"type":"datetime","pdo_type":2,"default":null,"nullable":true,"pkey":false},
"log_ts":{"type":"int","pdo_type":1,"default":null,"nullable":true,"pkey":false},
"filename":{"type":"varchar","pdo_type":2,"default":null,"nullable":true,"pkey":false},
"line_no":{"type":"smallint","pdo_type":1,"default":null,"nullable":true,"pkey":false},
"file_ts":{"type":"datetime","pdo_type":2,"default":null,"nullable":true,"pkey":false}
}
```

As you can see id has a "pkey":true entry so one could look at the fields from post then look at this and determine if IDENTITY_INSERT needs to set. Perhaps I will implement this. I worry this is above my paygrade.

I was asked to submit this here by xtra35 on stackexchange sorry if this is inappropriate.

thanks

**Comment by bcosca** [comment]
It appears like you are using a compound primary key and F3 sees it as such.

```
(`id`,`supply_id`)
```

**Comment by josephcrawley** [comment]
You are absolutely correct I missed that. I have removed primary key status from that row and now I am getting the following error

Internal Server Error

SQLSTATE[HY000]: General error: 102 Incorrect syntax near 'WHERE'. [102] (severity 15) [(null)]

[f3/lib/db/sql.php:202] PDOStatement->execute()
[f3/lib/db/sql/mapper.php:277] DB\SQL->exec()
[f3/lib/db/sql/mapper.php:319] DB\SQL\Mapper->select()
[f3/lib/db/cursor.php:175] DB\SQL\Mapper->find()
[f3/lib/db/sql/mapper.php:432] DB\Cursor->load()
[f3/lib/db/cursor.php:242] DB\SQL\Mapper->insert()
[app/models/Xrefs.php:24] DB\Cursor->save()
[app/controllers/XrefEntryController.php:36] Xrefs->add()
[index.php:14] Base->run()


If I examine the code in mapper at line 277



		echo $sql.'args= '.count($args).'ttl='.count($ttl).$ttl[0];
		$result=$this->db->exec($sql,$args,$ttl);
		$out=array();
		foreach ($result as &$row) {
			foreach ($row as $field=>&$val) {


I added the echo line for clarity and get this
SELECT [id],[changed_date],[status],[supply_id],[description],[unit],[hcpcs],[unitcost],[cap],[rev],[buq],[create_ts],[log_ts],[filename],[line_no],[file_ts] FROM [xrefs] WHERE args= 0ttl=1

So you the select statement has a where with no arguments. args is empty and ttl has one blank entry

**Comment by ikkez** [comment]
Please clear the application cache (because the old table schema might still be cached) and test once more with a newer F3 version (maybe your issue was fixed already)

**Comment by josephcrawley** [comment]
The update fixed it sorry to waste your time. Thanks for a wonderful product!
