### ISSUE TITLE
SMTP line length

### ISSUE THREAD

**Issue by ikkez** [bcosca/fatfree-core#215]
The SMTP RFC https://tools.ietf.org/html/rfc5321#section-4.5.3.1 says that the text line should have a maximum length of 1000.

We should probably add a chunk split in the smtp plugin to handle that.

**Comment by bcosca** [comment]
`chunk_split` may not be appropriate for cases like HTML email. I think `wordwrap` is more up to the job.

**Comment by KOTRET** [comment]
Notice that wordwrap's `$cut`-param must be `TRUE`.
Are there sideeffects when encoding a file for transfer like unwanted splitting a chunk below 1000 length due to base64-chars that are treated as word boundary? What about `<pre>`-tags in html mails?

**Comment by bcosca** [comment]
Chunked base64 encoding is a non-issue. It's quote-printable that may cause problems if text lines exceed the limit, but this can be controlled at the app end - not the SMTP plugin.

**Comment by SylwesterZarebski** [comment]
It should be also noted, that 1000 characters (bytes) limit apply to lines send to SMTP server, not original ones, which could be transformed by quoted-printable encoding and grows up - this "expanding" could be easily seen with multi-byte UTF-8 words.

For quoted-printable encoding You could use soft line breaks - just = on end of line:
https://en.wikipedia.org/wiki/Quoted-printable - see Example.
