### ISSUE TITLE
INI config file didn't loaded correctly on PHP5

### ISSUE THREAD

**Issue by chez14** [bcosca/fatfree-core#222]
Let me confirm this, is the INI config file can get loaded on php5 correctly? for some reason it gives me an error whenever i use PHP5.

Some of my school's server are running php5, and i can't just update it into php7.

[Here's my boilerplate](https://github.com/chez14/f3-boilerplate) for making those projects, and this is the [config loader](https://github.com/chez14/f3-boilerplate/blob/master/app/config.php), i use this kind of hierarchy for my projects, can you tell me, where's my mistake?

Thank you!

**Comment by Rayne** [comment]
Please post the error message/trace and name the affected PHP and F3 versions.

**Comment by chez14** [comment]
@Rayne [Try this](http://nosurat.labftis.net/). This is using exactly that boilerplate.

from the `composer.json`:
```
    "require": {
        "bcosca/fatfree-core": "^3.6",
        "rafamds/f3-falsum": "^2.6"
    },
```

`php --version`
```
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

It seems `routings.ini` didn't get loaded.

**Comment by chez14** [comment]
The routings are loaded. I'm sorry, this was a bogus.

I wrongly named the `template.php` as `Template.php`.

**Comment by chez14** [comment]
Wait, it's not really a bogus, these routings didn't work on PHP5. This is the real reason why i'm confused.

```ini
[routes]
GET /=Controller\App->get_hello
```

You can clone [this](https://github.com/chez14/f3-boilerplate) to try it on your server. Please, use php5:
```
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```
