### ISSUE TITLE
Publish PHP 7.2 compatible release

### ISSUE THREAD

**Issue by jtojnar** [bcosca/fatfree-core#226]
PHP 7.2 is almost here so it would be great to release a new version including https://github.com/bcosca/fatfree-core/commit/dce9d6e0cb5596004591c1bf7e5867afad411aeb. Some of our users are already reporting the incompatibility.

**Comment by ikkez** [comment]
I also think we should release something soon @bcosca @xfra35 @Rayne @KOTRET @sn0opy 
PHP 7.2 should be released end of november, so let's smash some bugs and tie a nice little patch release :)

**Comment by zachrattner** [comment]
Any update on this? PHP 7.2 is out now.

**Comment by jtojnar** [comment]
3.6.3 was released.
