### ISSUE TITLE
reset cached sql result doesnt work with memcache

### ISSUE THREAD

**Issue by durip** [bcosca/fatfree-core#233]
cache setting in config.ini
`CACHE="memcache=localhost:11211"`

run sql command
`$db->exec($sql, null, [3600,'customCacheTag']);`

now I want to clear cache in other class/function
`Cache::instance()->reset('customCacheTag');`

it doesnt work, problem is function memcache_get_extended_stats() used in Cache->reset class. PHP MANUAL Warning: The cachedump stat type has been removed from the memcached daemon due to security reasons. So its not possible to get all keys from memcache.
Possible solution: Cache::instance()->clear('customCacheTag') but key name must be only cache tag name

**Comment by xfra35** [comment]
I'm wondering where this error is coming from, as cachedump is still present in memcached [source code](https://github.com/memcached/memcached/blob/7f4e0246e5c27baa9a7a690e5905f5ee56b80ece/memcached.c#L3196). There's a configuration setting to disable it, but that's not the [default](https://github.com/memcached/memcached/blob/7f4e0246e5c27baa9a7a690e5905f5ee56b80ece/memcached.c#L257) setting and the error message would be "stats cachedump not allowed".

Can you trying replacing `memcache_get_extended_stats` with `memcache_get_stats` in [Cache->reset()](https://github.com/bcosca/fatfree-core/blob/ad5d9790eddc0d732b4caeb5c71af242126febb6/base.php#L2556) to see if it helps?

**Comment by durip** [comment]
I try use memcache_get_stats and still same behavior (cache tag doesnt reset), no error message.
Then I try this
`$slabs = memcache_get_stats($this->ref,'slabs');
 foreach (array_filter(array_keys($slabs),'is_numeric') as $id) {
    $data = memcache_get_stats($this->ref, 'cachedump', $id);
    print_r($data);
    if (is_array($data))
       foreach (array_keys($data) as $key)
          if (preg_match($regex, $key))
             memcache_delete($this->ref, $key);
}`

and $data variable contains Array ( [CLIENT_ERROR] => stats cachedump command disabled )

So my hosting provider disable cachedump I guess

**Comment by xfra35** [comment]
Ok so that means the `Cache->reset` command works with the `memcache` extension only if the `memcached` server hasn't been launched with the `-X` flag (disabling the *cachedump* stat).

I've mentioned that in the docs: https://github.com/F3Community/F3com-data/commit/8514abf1470c5ab04c06fbaeb60e37ca38014f68

For your case, try the `memcached` extension, if it's available on your server, otherwise you're left with the filesystem cache.
