### ISSUE TITLE
reset cached sql result with xcache reset complete f3 cache

### ISSUE THREAD

**Issue by durip** [bcosca/fatfree-core#234]
f3 cache set to xcache

run sql command
`$db->exec($sql, null, [3600,'customCacheTag']);`

now I want to clear cache in other class/function
`Cache::instance()->reset('customCacheTag');`

f3 reset complete cache. Problem is in function Cache->reset
`xcache_unset_by_prefix($this->prefix.'.');`
$suffix variable contain cache tag name ...

**Comment by xfra35** [comment]
I've tried a refactor of `Cache->reset()` for XCache: https://github.com/bcosca/fatfree-core/commit/8d10edc839cb8f47e1bf8c9351595b438c22b4d0 but I can't test it myself.

Can you test it please?

**Comment by durip** [comment]
I make test. Now when I try command
`Cache::instance()->reset('customCacheTag');`

error page is display:

XCache Authentication Failed

You're not authorized to access this page due to wrong username and/or password you typed.
The following check points is suggested:

    Be aware that `Username' and `Password' is case sense. Check capslock status led on your keyboard, and punch left/right Shift keys once for each
    Make sure the md5 password is generated correctly. You may use mkpassword.php
    Reload browser cache by pressing F5 and/or Ctrl+F5, or simply clear browser cache after you've updated username/password in php ini.

Check XCache wiki page for more information.

**Comment by durip** [comment]
I figure out that this error mesage "XCache Authentication Failed"
is because my hosting provider has setting in php.ini
`xcache.admin.enable_auth = on`

I thing almost every hosting has this setting for safety ...

**Comment by xfra35** [comment]
Oh indeed. What a shame.

Other librairies such as [Doctrine](https://github.com/doctrine/cache/blob/3ceefd4e7c8e575f53a5aaa346988938afa2c788/lib/Doctrine/Common/Cache/XcacheCache.php#L88) throw an error if that setting is enabled.

I've modified the code to reset by suffix only if that setting is disabled:
https://github.com/bcosca/fatfree-core/commit/0436a4e312a6de684041a94e4eef10e3f2295b13

I'll add a mention about it in the docs.

**Comment by xfra35** [comment]
Done in https://github.com/F3Community/F3com-data/commit/ccd41ade6eb2caf6c12a0e07dd390e87099cc720

We'll mention the ini setting when the new release will come.
