### ISSUE TITLE
PHP 7.2 - Cannot change cache limiter when session is active

### ISSUE THREAD

**Issue by zachrattner** [bcosca/fatfree-core#238]
I'm trying to upgrade from PHP 7.1 to 7.2. I've tried both v3.6.2 and v3.6.3 on PHP 7.2, and I'm getting the same error initializing sessions in both cases. PHP 7.1 works fine. 

My application code handles sessions on its own, outside of F3. The application calls `session_start` before F3 is initialized, which causes the following error in PHP 7.2:

```
session_cache_limiter(): Cannot change cache limiter when session is active
```

It seems base.php configures the session without first checking to see if a session has already been started:

1. [`session_cache_limiter`](https://github.com/bcosca/fatfree-core/blob/b35fe7ae88f6f3667c50c36563b50e5a1ec36bb1/base.php#L2274)
2. [`session_set_cookie_params`](https://github.com/bcosca/fatfree-core/blob/b35fe7ae88f6f3667c50c36563b50e5a1ec36bb1/base.php#L2284)

According to the [docs](https://fatfreeframework.com/3.6/framework-variables), the intent appears to be that the session should be able to be manipulated directly if desired: 

> Setting the Fat-Free equivalent of a PHP global like SESSION also changes PHP's underlying $_SESSION. Altering the latter also alters the framework counterpart.

If my understanding is correct, shouldn't the session be conditionally initialized in F3 only if it has not already been configured by the time the framework is initialized?

Making this change in base.php is working for me:

```
// Check to see if a session has already been initialized before attempting to configure it
if (session_status() !== PHP_SESSION_ACTIVE) {
     session_cache_limiter('');
     $jar = [
         'expire' => 0,
         'path' => $base ?: '/',
         'domain' => is_int(strpos($_SERVER['SERVER_NAME'], '.')) &&
         !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP) ?
             $_SERVER['SERVER_NAME'] : '',
         'secure' => ($scheme == 'https'),
         'httponly' => TRUE
     ];
     call_user_func_array('session_set_cookie_params', $jar);
 }
```

**Comment by soyleung** [comment]
Good!
I have found this error, and published in https://github.com/ikkez/fabulog/issues/19
Thought it was PHP7.2 BUG

**Comment by ikkez** [comment]
I'm not sure if this is an upstream bug in the newest PHP version or not.. the referenced issue https://bugs.php.net/bug.php?id=75628 doesn't give an answer yet. Nevertheless I've added a fix in a pending PR for this to work around the issue.

**Comment by ikkez** [comment]
should be fixed now

**Comment by zachrattner** [comment]
@ikkez Do you have an ETA when this fix will be available in Packagist?

**Comment by ikkez** [comment]
Well why waiting so long right? I think we can sort some things out and push 3.6.4 next week hopefully

**Comment by Rayne** [comment]
@zachrattner The fix is already available at Packagist in the `dev-master` branch.

```bash
composer require bcosca/fatfree-core dev-master
```

**Comment by zachrattner** [comment]
ETA on it being added to a stable branch?

**Comment by WilliamStam** [comment]
would be nice if it was released to main. a few months later and still sitting with this. using ```"bcosca/fatfree": "3.*",``` in composer. using ```dev-master``` in prod is a big no no (had an interesting "experiance" with another project using dev-master - NEVER AGAIN)

**Comment by Rayne** [comment]
The latest version (3.6.4) has the fix included: https://github.com/bcosca/fatfree-core/releases/tag/3.6.4
