### ISSUE TITLE
Float passed to setcookie as $ttl parameter instead of int

### ISSUE THREAD

**Issue by Alanaktion** [bcosca/fatfree-core#240]
Calling `Base::set` to set a cookie with a `$ttl` causes a float to be passed to the setcookie function, which throws a warning on some PHP versions.

For example, this code:
```php
Base::instance()->set('COOKIE.example', 'value', 3600);
```

causes a setcookie() call like this:
```php
setcookie('example', 'value', 1515090741.903516, '/', 'example.com', false, true);
```

The third parameter should be an int instead of a float according to the PHP documentation, and it does cause warnings on some PHP configurations, like:
```
Warning: setcookie() expects parameter 3 to be int, float given
```

This could be fixed with something as simple as adding an extra line before the `call_user_func_array` call, but there might be a better way of doing it.

```php
// Base.php line 360
// ...
if ($ttl)
	$jar['expire']=$time+$ttl;
$jar['expire']=(int)$jar['expire']; // added line
call_user_func_array('setcookie',[$parts[1],$val]+$jar);
// ...
```

**Comment by xfra35** [comment]
Fixed
