### ISSUE TITLE
Session table creation fails with charset utf8mb4 in MySQL 5.6

### ISSUE THREAD

**Issue by bjugan** [bcosca/fatfree-core#241]
If db based sessions are used with MySQL 5.6 and the charset is utf8mb4, the creation of session table will fail with the following error:

`Error Code: 1071. Specified key was too long; max key length is 767 bytes`

As far as I can see this error referes to the primary key session_id that is varchar(255). With utf8mb4 (4 bytes/char) this will break MySQL 5.6's limit of 767 bytes for a primary key (4 bytes * 255 chars = 1020 bytes).

Could session_id field change to varchar(191 or less)?

In MySQL 5.7 the limit is increased to 3072 bytes and problem is solved, but I'm stuck with 5.6.

**Comment by KOTRET** [comment]
Why you encode the session_id with utf8mb4? Change the collation to solve this problem.

**Comment by bjugan** [comment]
Yes, I can use an other collation on the session_id, but the session table is created **automaticly** the first time you use a database based session and the session table will use the default collation set on the database.

When the default collation on the database is utf8mb4 (i won't change that) the automatic session table creation will fail and give the error as described in my first comment. Then you have to create the table manually or change the source code.

As a temporary solution I have changed db/sql/session.php line 184 to

`$tab.$db->quotekey('session_id').' VARCHAR(190),'.$eol.`

Or am I missing something here?

**Comment by xfra35** [comment]
The reason why the `session_id` length has been increased is detailed here: https://github.com/bcosca/fatfree/issues/950

Here are a few suggestions to handle this issue:

1. we force the charset of the session table (UTF-8 or even Latin1 should be enough)
2. we lower down the `session_id` length to a "reasonable" length
3. we add a parameter to control the length of `session_id`
4. we don't do anything... after all this is a restriction of MySQL<=5.6

**Comment by bjugan** [comment]
Ah, sorry, haven't seen issue 950 (even if I tried to find issues related to my issue). 

**Alternative 2** may then be bad because it breaks the possibility in php 7.1 to have a session id with 256 chars and I guess it's more important to support new versions of PHP than old versions of MySQL.

**Alternative 3** is perhaps to much work compared to the size of this "problem".

**Alternative 1 or 4** is fine with me.  Actually, I'm leaning towards 4 because I'm not sure about the consequences of having different collations on different tables. Could give errors like "illegal mix of collations".

I'm using MySQL 5.6 because cPanel servers and Amazon Aurora don't support 5.7 but I think they will upgrade this year and until then I can handle this issue manually.
There is also a big chance I'm the only person with this issue :-)

**Comment by KOTRET** [comment]
> I'm not sure about the consequences of having different collations on different tables. Could give errors like "illegal mix of collations".

The session table lives on its own, you don't have any foreign keys so that queries would crash because of a different collation. Actually selecting another collection could influence the performance (positively): the database has to read / write less bytes for the key with a "smaller" collation

**Comment by bjugan** [comment]
Yes, it lives on its own, but couldn't there be situations where you want to save the session_id in another table (for example some user table) and do a sql JOIN between this table and the session table?
Not that I have implementet this in my solutions, but can't say for sure it will never happen.

**Comment by KOTRET** [comment]
In this case you'd change the collation in the user table too ;)
Anyway - guess you can close the issue, as @xfra35 provided some solutions for your situations.
Since the table is created only once, this shouldn't be a challenge :)
