### ISSUE TITLE
Routing to a View/Preview class derivative is broken

### ISSUE THREAD

**Issue by bcosca** [bcosca/fatfree-core#249]
`View->construct()` is not invoked when routing directly to a View/Preview (or even Template) class descendant, which means the class is never instantiated; hence `$this->fw` is always `NULL`.

Commit 15cf2b6 is to blame.

**Comment by bcosca** [comment]
Hmm, you're right. The difference is that now we have to call `parent::__construct()` explicitly in a View/Preview/Template class derivative.

**Comment by ikkez** [comment]
The point of https://github.com/bcosca/fatfree-core/commit/15cf2b6ce4e40aa08da415437c569fba8770b9ac was to reduce calls to Base::instance. It's called unnecessary often during template rendering... I had a search result page which a lot of tokens which called like 600 times the ::instance method...

**Comment by ikkez** [comment]
> Hmm, you're right. The difference is that now we have to call parent::__construct() explicitly in a View/Preview/Template class derivative

Yes I have added this in https://github.com/bcosca/fatfree-core/commit/15cf2b6ce4e40aa08da415437c569fba8770b9ac

**Comment by bcosca** [comment]
Not a big deal.
