### ISSUE TITLE
 oauth2 returns null on some endpoints

### ISSUE THREAD

**Issue by bucs-fan813** [bcosca/fatfree-core#250]
```
$auth_domain = 'https://stackoverflow.com';
$oauth2 = new \Web\OAuth2();
$oauth2->set('redirect_uri', 'example.com');
$oauth2->set('client_id', '12345');
$oauth2->set('code', $_GET['code']);            
$oauth2->set('state', $_GET['state']);
$oauth2->set('client_secret', 'SEEKRET');
$uri = $oauth2->uri($auth_domain . '/oauth/access_token');
$request = $oauth2->request($uri, 'POST');
//$request will be null (see attached).
//However if you debug $response in https://github.com/bcosca/fatfree-core/blob/e49cb8586913367e04212b511e438dc5388a9a27/web/oauth2.php#L64, 
//there is actually a 200OK response with the token in $response['body'] as plaint text.
```
On some oauth2 implementations like [stackexchange](https://api.stackexchange.com/docs/authentication) `\Web\OAuth2->request()` will return null even though the endpoint responded with 200OK and the token. The return logic for Web\OAuth2->requests needs to be revised. Stack exchange documentation says that I should use https://stackoverflow.com/oauth/access_token/json however the /oauth/access_token endpoint behaves similarly to the closed system this app will be used on. There is not a JSON specific endpoint available on the closed system. [json_decode](http://php.net/manual/en/function.json-decode.php) will return null if the json cannot be decoded or if the encoded data is deeper than the recursion limit.

**Comment by bucs-fan813** [comment]
Using 
![image](https://user-images.githubusercontent.com/7397288/39261160-a1696646-4889-11e8-8193-d7a813db040b.png)

**Comment by KOTRET** [comment]
mhm, the methods return is a bit squishy: it states a string or false is returned, actually it can return
* a string
* array (if the body is `json_decode`-able)
* or false.

for stackexchange it looks like the format is `k=v;k=v`.

imho a fix should take the content type into account and `json_decode()` only if the content type is `application/json`.

**Comment by bucs-fan813** [comment]
> mhm, the methods return is a bit squishy: it states a string or false is returned, actually it can return

indeed! partially due to the fact that `json_decode` can return `null` but the ternary in `request()` assumes `json_code` will always return an object.
