### ISSUE TITLE
Basket->erase by _id ?

### ISSUE THREAD

**Issue by ptdev** [bcosca/fatfree-core#260]
Hi, I just started using the Basket class for a simple shopping cart. The class automatically creates an _id field for each cart entry.

But then apparently we cannot use said _id on the erase() method. ( e.g.: ```Basket->erase('_id', $f3->get('PARAMS.id'))``` ) which is what a "remove from cart" functionality would probably use.

So, how to remove single items from the cart?

Right now I'm using ```unset($_SESSION['some-key'][$f3->get('PARAMS.id')])``` which works, but feels a bit weird unsetting directly from $_SESSION.

Is this by design? Am I missing something? Thanks

**Comment by bcosca** [comment]
Unit test to accompany above commit in bcosca/fatfree@4aa7113

**Comment by bcosca** [comment]
Please close this issue if the solution is satisfactory.

**Comment by ptdev** [comment]
Thanks! Can't really test it now, but seems to be 100% satisfaction on that one, as usual 👍
