### ISSUE TITLE
i keep getting 'bad chars in url' when doing web->request

### ISSUE THREAD

**Issue by rxhector** [bcosca/fatfree-core#273]
https://github.com/bcosca/fatfree-core/blob/1c94f0d782292720a743a89ca2ec1016b2f2931e/web.php#L659

i fixed my issue by trmming the $url 

$result=$this->{'_'.$this->wrapper}(trim($url),$options);

**Comment by ikkez** [comment]
`trim` is not multibyte-safe. If you'd like you trim your uri, why not doing it on the method call: `$web->request(trim($url));`?

**Comment by rxhector** [comment]
it's just odd
a simple request like 

$page = \Web::instance()->request("http://www.us-proxy.org/");

gives me the error and i have to trim in the web.php

**Comment by ikkez** [comment]
I have no problem here with that code line. Inadvertently typed an invisible half-space maybe? Remove that line an write it again, just to be sure ;)
