### ISSUE TITLE
$f3->set(...$ttl=0) ignore caching if $ttl is not set

### ISSUE THREAD

**Issue by lsafelix75** [bcosca/fatfree-core#280]
From the code: base.php, i see the following.
if i want to save a variable via session with $f->set('SESSION.x', 'xxxx') without defining ttl, the value is not cache at all for reuse. Is this intentional? From the documentation, if $ttl=0, it mean infinite but it is not the case based on the code. 

```
function set($key,$val,$ttl=0) { 
....
if ($ttl)
      // Persist the key-value pair
      Cache::instance()->set($this->hash($key).'.var',$val,$ttl);
```

**Comment by ikkez** [comment]
Hi there.. well.. some things are wrong here:
-  you refer to the documentation of Cache->set, where ttl=0 means infinite
-  the posted code however is from Base->set and not Cache->set
-  caching a SESSION var is a bad idea and should actually be blocked by the framework
-  the ttl doesnt effect single session variables, as the whole session lifetime is being controlled by `JAR.lifetime` instead, making the usage of $ttl with f3->SESSION superfluous.
