### ISSUE TITLE
3.7.1 - SQL Mapper no autohydrate on insert/update

### ISSUE THREAD

**Issue by diapolon** [bcosca/fatfree-core#292]
Hi, with latest version, after calling **save()** method,  F3 wont auto-hydrate the object.
Example:
i have a table with id primary key,
`
foreach($data as $key => $value) $this->set($key, $value);
$this->save();
echo $this->id;
`
with 3.6.x it return current id if update or new id if insert.
With 3.7.x it return null or empty

**Comment by ikkez** [comment]
duplicate bcosca/fatfree#1175

I'm still not able to reproduce this.. works fine in 3.7.1 and dev-master. I need more information about your model and an helpful context.

**Comment by ikkez** [comment]
I found out that when you set id = 0, it'll cause the mapper to not reload since 3.7.1.. if that's a bug or not will be discussed in bcosca/fatfree#1175 .. as quick workaround for you: dont set id to 0... doesnt make sense anyways. thank you
