### ISSUE TITLE
Suggestions for Base::redirects

### ISSUE THREAD

**Issue by soyleung** [bcosca/fatfree-core#294]
I try to use base:: redirects to jump to other pages.

But I found that there was too much consumption of $init resources in redirects.

So I changed the $init mode, read it statically, and found that the optimization was better.

I don't know what this is about.

1.Add to
```
+static
+    $init;
```
2,delete in private
```
-    $init;
```
3,replace
```
$this->init;
```
to
```
self::init;
```

**Comment by ikkez** [comment]
This doesn't make much sense. Can you explain the WHY a bit more detailed please?!
