### ISSUE TITLE
Ad-hoc field null problem with Twig

### ISSUE THREAD

**Issue by joseffi** [bcosca/fatfree-core#310]
I am using f3 3.7.2 with Twig 3.1.1.
When an ad-hoc Mapper field returns null, rendering the Twig template containing that field will return this error:

```An exception has been thrown during the rendering of a template ("call_user_func_array() expects parameter 1 to be a valid callback, no array or string given")```

For example: 

```php
class product extends \DB\SQL\Mapper {

    function __construct() {
        $this->supplier_name = "SELECT name FROM supplier WHERE id = supplier_id";
    }

}

$p = new product;
$p->load(["id=:id", [":id"=>"product123"]]);

global $twig;
echo $twig->render("product_detail.php", ["product" => $p]);
```
And the template:
```html
{{ product.supplier_name }}
```

If supplier_id is not set in the product, the ad-hoc field supplier_name becomes null, resulting in the above PHP error.
As a workaround, I edited magic.php, line 60

From
```php
($this->exists($key) && $this->get($key)!==NULL);
```
into
```php
$this->exists($key);
```

Thus reverting the function offsetexists() back to v3.6.5.  
May I ask what was the reason for the null checking in v3.7+?

**Comment by joseffi** [comment]
I should add, offsetexists() on a null ad-hoc field returns
true in 3.6.5, and
false in 3.7.2

**Comment by ikkez** [comment]
The change in magic.php was made to ensure some fundamentals are working correctly, like:

```php
$mapper->foo = null;

// expected
isset($mapper->foo) === FALSE
```

see https://github.com/bcosca/fatfree-core/commit/e0bcd7fc1f07355574df3ceee7f3100dbee9222f for me details

**Comment by geniuswebtools** [comment]
@joseffi, can you use the COALESCE() in your SQL statement?

SELECT COALESCE(name, 'Unknown') FROM supplier WHERE id = supplier_id

**Comment by n0nag0n** [comment]
I've run into this exact problem before. One way I got around it was instead of doing a LEFT or RIGHT JOIN, I'd do an INNER JOIN so if the field was empty, NULL wouldn't show up. 

Ultimately though I've since backed away from Twig. It's cool and all, but it has some quirks. And I always kept going back to the docs pages cause I could never remember the syntax. Adding filters was less than fun and it only became "ok" to develop with Twig in general. I've since started using the built in templating system in Fat-Free and while it still has a couple things I'm not a huge fan of, overall it gives me greater flexibility in what I want it to do. If you haven't, I'd highly recommend giving the built in templating system a go.

**Comment by joseffi** [comment]
@ikkez thanks for your explanation
@geniuswebtools that works too, thanks
@n0nag0n I appreciate the suggestion, but Twig suits our purpose better for now.  I'll live with the quirks.

**Comment by joseffi** [comment]
Hi, excuse me for reopening this issue.

Apparently, the cause is 
call_user_func_array() being called with NULL as the first argument by \DB\SQL\Mapper::__call here in line 153:
```
	function __call($func,$args) {
		return call_user_func_array(
			(array_key_exists($func,$this->props)?
				$this->props[$func]:
				$this->$func),$args
		);
	}
```

I've fixed this by overriding array_key_exists 
```
<?php
namespace DB\SQL;

function call_user_func_array($callback, $args) {
    if (!$callback) return null;
    return \call_user_func_array($callback, $args);
}
```

But wouldn't it be a good idea to implement this checking in \DB\SQL\Mapper::__call instead?

**Comment by ikkez** [comment]
Actually I'm wondering why this __call method is there anyways.. for properties, there're the magic get and set methods, and for methods.. well calling `$this->$func` doesn't make much sense in a magic __call method that is only executed when the called method does not exist... So i think this can be removed completely. Thoughts?

**Comment by n0nag0n** [comment]
_Hesitantly gives a :+1: _ I agree. Feels like double duty.

**Comment by ikkez** [comment]
fixed in latest commit
