### ISSUE TITLE
Postgresql DB Name with space breaks SQL Mapper

### ISSUE THREAD

**Issue by ykgamma** [bcosca/fatfree-core#316]
When creating a DB\SQL object, spaces in the dbname are escaped by \ characters as required by the DSN. However, when the dbname is extracted from the DSN, the escape \ characters are not removed. 

This will cause the schema method to not return any fields as table name will have \ characters in the query. This results in the Mapper not having any fields when accessed.

**Comment by ikkez** [comment]
fixed
