### ISSUE TITLE
Undefined index: trace in base.php on line 1379

### ISSUE THREAD

**Issue by jtojnar** [bcosca/fatfree-core#323]
If `!$this->hive['DEBUG'] && $this->hive['CLI']`, the `$error` variable will not contain `trace` key, resulting in a warning in PHP 8:

https://github.com/bcosca/fatfree-core/blob/3e23ae05384b2f830e99c5888b94118819ed948b/base.php#L1379

This has been introduced in 3.7.3 by https://github.com/bcosca/fatfree-core/commit/fea7561b456ad8187392554f73f2a13b2cf69892.

cc @ikkez

**Comment by ikkez** [comment]
fixed in latest commit. Release scheduled in 2021 Q1
