### ISSUE TITLE
Php 7.1.26-mh2

### ISSUE THREAD

**Issue by dgaenko** [bcosca/fatfree-core#330]
i try framworks on php 7.1.26 and have next:
Internal Server Error
Fatal error: Unknown: Use of mbstring.internal_encoding is deprecated 

[mbstring screen](https://d.radikal.ru/d30/2107/64/747fa0149293.jpg)

**Comment by xfra35** [comment]
You need to remove the `mbstring.internal_encoding` line from your php.ini file.
This has nothing to do with the framework.
