### ISSUE TITLE
When can fatfree-core support PHP8.1?

### ISSUE THREAD

**Issue by cybrobin** [bcosca/fatfree-core#334]
When can fatfree-core support PHP8.1?

**Comment by ikkez** [comment]
I'm in the making of a dockerized development container that supports running multiple php versions at the same time, so testing, developing and running the unit tests is easier for everyone. Once I've sorted this out, we're gonna fix the 8.1 compatibility ASAP.

**Comment by ikkez** [comment]
PHP 8.1 fixes committed: https://github.com/bcosca/fatfree-core/commit/aa07384bd91ac11463f9a7e5d6409188a8496cc0
We also have a development container now 🥳   https://github.com/f3-factory/fatfree-dev
