### ISSUE TITLE
reroute() trims port number if domain is localhost:8000

### ISSUE THREAD

**Issue by pixeline** [bcosca/fatfree-core#343]
(using latest stable 3.8.0) 

When working locally, my app runs on 'localhost:8000' as set in the .ini file:

```
WWWROOT=http://localhost:8000
```

Everything runs as it should until i use `reroute` as in : 

``` 
    $f3->reroute('@quote_action(@action=view,@author='.$author->slug.',@slug=' . $quote->slug . ')');

```

it redirects correctly, but the port is stripped out of the URL.

**Comment by ponasromas** [comment]
Try to quote:

WWWROOT="http://localhost:8000"

**Comment by ikkez** [comment]
Cannot reproduce this issue. Also I'm not sure where your ini came from or how your environment is set up. Hence there's nothing we can do here.
