### ISSUE TITLE
`alias()/reroute()` and params requiring proper `urlencode()`

### ISSUE THREAD

**Issue by kumy** [bcosca/fatfree-core#345]
I think there is a problem with `alias()`/`reroute()` function when it build the url using known parameter from current request, and when a parameter need to be url encoded.

**Actual result**
An "invalid" url as it doesn't properly use `urlencode()` on the url parameters

ex: 
- input: `/a/bar%25`
- output: `/a/bar%` <- the percent sign is not encoded

**Expected result**
A valid url show be generated, with the parameter properly encoded

ex: 
- input: `/a/bar%25`
- output: `/a/bar%25`

**Step to reproduce**
I've extracted this part of code to reproduce the issue:
```php
<?php

require __DIR__.'/../../vendor/autoload.php';

$f3 = \Base::instance();
$f3->route('GET /a/@foo',
    function(\Base $f3, $params) {
        echo 'Input params:'.PHP_EOL;
        var_dump($params);

        echo PHP_EOL.'Generated url:'.PHP_EOL;
        var_dump($f3->alias('alias1'));
        $f3->reroute('@alias1');
    }
);
$f3->route('GET @alias1: /b/@foo',
    function(\Base $f3, $params) {
        var_dump($params);
    }
);

$f3->run();
```

```
$ curl "https://xxxxx/a/bar%25" 
Input params:
array(2) {
  [0]=>
  string(7) "/a/bar%"
  ["foo"]=>
  string(4) "bar%"
}

Generated url:
string(7) "/b/bar%"  // <- missing properly encoding
```

```
$ curl "https://xxxxx/a/baz%25" -v 2>&1 |grep -i loca
< location: https://xxxxx/b/baz%
```

```
$ curl "https://xxxxx/a/baz%25" -L
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**Notes**
I had the expected result if I use `urlencode()` inthe return statements of the anonymous function inside the `build()` function.

**Comment by ikkez** [comment]
should be fixed in latest commit. unit test added at https://github.com/f3-factory/fatfree-dev/commit/1093950de1b485b6b772cad5569a91e3f84da5f2
