### ISSUE TITLE
PHP 8.1 Undefined array key

### ISSUE THREAD

**Issue by ieteo** [bcosca/fatfree-core#349]
Hi,

the conditional segment `check` in template e.g.

`<check if="{{  @SESSION.foo }}">`

translates in compiled template to:

`<?php if ($SESSION['foo']): ?>`

which gives in PHP 8.1 **Undefined array key** error if the variable do not exists

In my opinion it should translate to:

`<?php if (isset($SESSION['foo'])): ?>`

More on this topic here: 
https://phpshowcase.com/question/dealing-with-php-8-1-warning-for-undefined-array-key

Kind Regards
Eteo

**Comment by paclucio** [comment]
Hi @ieteo,

It's no a bug, the template directive accepts any conditional expression such like `<check if="{{ @foo === @bar }}"`.

If you need to check if a variable is available you should `<check if="{{ isset(@SESSION.foo) }}">`.

**Comment by ieteo** [comment]
Hi @paclucio,

I see 😳, thanks for the info.
