### ISSUE TITLE
PHP 8.1 / str_replace Argument #3 beeing NULL throws error

### ISSUE THREAD

**Issue by wildtierschweiz** [bcosca/fatfree-core#351]
https://github.com/bcosca/fatfree-core/blob/d13f60615efecc37cfcb14b223716903823a20f8/db/sql.php#L128

Hi There,

I noticed a problem in the db/sql class: the str_replace instances should be null safe. I think this mainly applies to line 128, when a float value is NULL. With other datatypes it should be ok.

Thank you!

**Comment by ikkez** [comment]
I'm not quite sure how this could happen, as the line above is already checking for non-NULL values:

https://github.com/bcosca/fatfree-core/blob/d13f60615efecc37cfcb14b223716903823a20f8/db/sql.php#L127-L128

Do you use the latest released F3 version?

**Comment by wildtierschweiz** [comment]
Alright ... I have 3.8.0 installed, where it only checks for string:
if (!is_string($val))

i might go for @dev then.

Thanks ikkez, good to have you around.
