### ISSUE TITLE
[BUG] \Template doesn't render text node 0 (zero)

### ISSUE THREAD

**Issue by paclucio** [bcosca/fatfree-core#354]
Given `<check if='{{ @foo == @bar }}'><true>1</true><false>0</false></check>`
the zero in the false tag is not printed.

The bug is on `\Template->parse()` [line 280](https://github.com/bcosca/fatfree-core/blob/master/template.php#L280)

`$match[1]` if is a zero evaluates to false, and isn't added to the `$tree`.
`if (strlen($tmp) || $match[1])` needs to be `if (strlen($tmp) || isset($match[1]))`

Thank you ;)

**Comment by ikkez** [comment]
fixed
