### ISSUE TITLE
TZ auto detection

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#68]
Hi,

[Currently](https://github.com/bcosca/fatfree-core/blob/master/base.php#L2137), TZ is autodetected using `ini_get('date.timezone')`.

I've just encountered the case on a server where this autodetection didn't work because `ini_get('date.timezone')` returned nothing. On the other hand, `date_default_timezone_get()` did return the correct timezone, so why don't we use `date_default_timezone_get`?

**Comment by bcosca** [comment]
Good idea. PHP >5.4 has a different autodetection mechanism, so `ini_get('date.timezone')` may be outdated.
