### ISSUE TITLE
Content-Length header

### ISSUE THREAD

**Issue by ikkez** [bcosca/fatfree-core#73]
there is no `Content-Length` header being send for routes in the `run` function. I'm not sure why it's missing, but I think we should add it.

**Comment by xfra35** [comment]
That's a job for the web server. PHP cannot be aware of how long its response will be after server post-processing (gzipping for example).

**Comment by ikkez** [comment]
Ah okay, understand. I was just wondering about that, because after reviewing the Benchmark app for round 11, I noticed that the test was warning about missing header information. So could that be a nginx config issue then?

**Comment by xfra35** [comment]
Actually the data is sent via the "chunked transfer encoding", so the Content-Length header is irrelevant in that case.

**Comment by xfra35** [comment]
Isn't the warning about a wrong Content-Type header? I see `Content-Type: text/html; charset=UTF-8` in the log, while a json response is expected.

**Comment by ikkez** [comment]
Hm. Good point, but the correct `Content-type: application/json` header is set correctly in all routes. Maybe it's just a HEAD preflight request, which is causing this.. and the plaintext route is correct with `text/html`, but the warning is occurs here too. I'll investigate when the vagrant clone is up and running locally
