### ISSUE TITLE
template parsing single tag elements

### ISSUE THREAD

**Issue by ikkez** [bcosca/fatfree-core#75]
I noticed that the [Template->parse](http://fatfreeframework.com/template#parse) method could act a little bit weird when you have a [registered tag handler](http://fatfreeframework.com/template#extend) and have a html element in your markup that only has a starting tag, without being properly self-closed. 

This **works**:
```html
<set key="val" />
```
but this **breaks** the markup:
```html
<set key="val">
```

This looks trivial and easy to solve by adding the `/ >` tag ending, but sometimes I don't recognize it immediately and this construct is eating up some of your subsequent html markup that just get lost. I have a tag handler on `<input>` fields, which are common, single tag elements that are HTML5 valid without being self-closed. 
I have no problem with adding the closing slash, but some skeleton frontend frameworks like h5bp, bootstrap, etc. are shipped with the simplified syntax `<input type="text" name="search">` and it isn't really reliable for plugin developers to force the rewrite of templates. 
I haven't found a fix for the [parse](https://github.com/bcosca/fatfree-core/blob/master/template.php#L270) method yet, but I can imagine that a bit juggling with `$stack` and `$depth` could do the trick.

**Comment by bcosca** [comment]
Let me see if I can help you with that.

**Comment by xfra35** [comment]
The dummy `$empty` argument looks misleading (as if an extra information is sent to the callback).

Why not adding an extra `$empty` property to the Template class, holding the list of empty tags? This would require to initialize it with `array('set','include')` and to add a third argument to the `extend()` method.

**Comment by bcosca** [comment]
That sounds logical. I'll see what I can do later.

**Comment by ikkez** [comment]
Ah okay, you try to skip increasing the `$depth` by using a flag from the handlers methods parameter. That's a neat hack, very creative ;) but the ReflectionFunction isn't properly working here, when you define a custom function as string like `Foo::renderATag`. And maybe there is a better way, not to use a reflection at all, as it might slow down the rendering a lot, when you handle a lot of tags. Let's have a look at the tag `$stack` again.. maybe we can find the needle.

**Comment by bcosca** [comment]
@xfra35 is right. This approach is indeed more optimal as it does away with all those dummy arguments and reflection.

**Comment by ikkez** [comment]
I couldn't sleep well last night because of this :D It took me a while to understand how this smart template parser was build, really very great work bong. 
But I thought that the root issue here must be somewhere in the way how the parser works. The way the node tree is currently build: 
when you find a tag the depths is increased and any further nodes are pushed into the current stack. And when a closing tag was found some reference magic happens. I tried another approach: when a starting tag was found (both empty & non-empty), the depths is not increased and the node moves into the stack. When a closing tag was found, it moves backwarts in stack to find the matching & still empty node, and pushed all node in between into the matching node. 
That way the tree is build more implicit, works with empty tags, you don't need extra arguments for tag handlers which is more intuitive and also allows support for tags that can be both.. empty or with content... who would need that? Our own website is already fired by a custom markdown tag https://github.com/F3Community/F3com/blob/master/inc/viewhelper.php#L29 that can be:
```html
<markdown>
# H1 Headline
</markdown>

<markdown src="content/home.md" />
```
So it would be nice to keep this possibility. Check my commit https://github.com/ikkez/fatfree-core/commit/a04371e9136c4baf99fce534054cc4cf41b65ede and tell me what you think. It seems to work great here, passes the unit tests and doesn't really need the `$depths` var anymore, though I wasn't able to remove that yet, as things started to fall apart. ^^

**Comment by xfra35** [comment]
Hey @ikkez,
I haven't looked at your code but I wanted to mention that the current codebase does support tags which can be both empty and not empty, such as `<markdown>`. You just need to declare them as non-empty tags. In other words, the `$empty` flag is intended for tags that are *always* empty and that we need to force close when they are not properly self-closed.

**Comment by ikkez** [comment]
Yes, I know. But the `empty` flag is actually just a workaround the problem that the parser is too strict. When you declare `$empty=true` than this works:
```html
<markdown src="content/block1.md" />
<markdown src="content/block2.md">
```
But than you loose the possibility to use the same tag with content inside. And if you leave `$empty=false` than this will work:
```html
<markdown>
# H1 Headline
</markdown>
<markdown src="content/home.md" />
```
But this will break your template:
```html
<div>
  <markdown src="content/home.md">
</div>
```

**Comment by xfra35** [comment]
But how could the parser know that `<markdown src="content/home.md">` is self-closed and `<markdown>` is not?

**Comment by ikkez** [comment]
It depends on, if a closing that is found or not. Every browser DOM Parser does it the same way. I have described that in https://github.com/bcosca/fatfree-core/issues/75#issuecomment-131055889 :D It took me about 3hours to understand how the parser works and find an alternative way of building the node tree that makes this possible. The key is that in [my approach](https://github.com/ikkez/fatfree-core/commit/a04371e9136c4baf99fce534054cc4cf41b65ede) the tree it flat first, but gains growth on finding closing tags. The current implementation is the other way round: it grows with opening tags (or stays flat on properly flagged empty tags), which leads to the described issue, becasue the parser don't know if there'll come a closing tag or not.

**Comment by xfra35** [comment]
If you rely on closing tags, will you still be able to handle nested tags?

Like:
```html
<markdown>
  <switch>
    <case>...
  </switch>
</markdown>
```

and:

```html
<markdown src="home.md">
  <switch>
    <case>...
  </switch>
```
?

**Comment by xfra35** [comment]
Well I don't know how you do this magic, but this seems to be working, even with complex scenarios :+1: 
Really need to dive into your code :D

**Comment by bcosca** [comment]
Wonderful job @ikkez! I've always thought a top-down parser was more efficient for this purpose and never thought a bottom-up approach would yield better performance. Great insight. Must have taken a while for you to understand the tiny gears in that template engine :)

**Comment by ikkez** [comment]
Yes I guess it's one of the most complicated looking parts of the framework, which revealed itself as doing a simple task after further studying. You are a genius that you have written that from the ground up. Maybe I'm good at finding improvements, but I wouldn't have any idea how to start building a template engine ^^

**Comment by bcosca** [comment]
Once you get to understand how it works, it shouldn't be difficult to write a DOM parser in C :)
