### ISSUE TITLE
DB-managed sessions autostart

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#89]
At the moment, Cache & DB-managed sessions are automatically started:
```php
$f3=require('lib/base.php');
new Session();// calls session_start()
$f3->run();
```
If you don't want that behaviour, you have to replace a single call to `new Session()` with a multitude of calls every time you need a session. This makes it difficult to move an existing codebase from one session handler to another.

Couldn't we remove that automatic start? Looking at the code, it looks like whatever comes after `register_shutdown_function('session_commit')` in the [constructor](https://github.com/bcosca/fatfree-core/blob/cec6b90cdb92a41f862ecc413860f476ad19d714/session.php#L164) could be moved into the `open()` method.

**Comment by bcosca** [comment]
This looks reasonable. Can you submit a PR for all session handlers?

**Comment by xfra35** [comment]
That was actually trickier than it looked. Cf. #94
