### ISSUE TITLE
drop mset for LOCALES

### ISSUE THREAD

**Issue by ikkez** [bcosca/fatfree-core#92]
Regarding this issue from the board https://groups.google.com/forum/#!topic/f3-framework/eDuCGUR1dBA we should think about not using `mset` here https://github.com/bcosca/fatfree-core/blob/master/base.php#L356 because `set` includes an existence check in the cache, that is triggered for each and every dictionary entry, which makes it slow for bigger lexicon files and is not really needed at all?!
I suggest to change the code to add lang keys in a more dumb way. maybe something like this:
```php
case 'LOCALES':
	if (isset($lex) || $lex=$this->lexicon($val))
		foreach ($lex as $key=>$val) {
			$ref=&$this->ref($this->hive['PREFIX'].$key);
			$ref=$val;
			unset($ref);
		}	
```

**Comment by xfra35** [comment]
That `Cache->exists()` seems to be costing at times, even with `CACHE` disabled. I came to this conclusion [here](https://github.com/bcosca/fatfree/issues/845#issuecomment-113659667), although I didn't understand how it could slow things down with a [simple](https://github.com/bcosca/fatfree-core/blob/master/base.php#L2204) `if (!$this->dsn) return FALSE`.

By the way, what's the purpose of that check? Can't we just remove it?
```php
if ($ttl)
  Cache::instance()->set($hash,$val,$ttl);
```
looks fine to me..

Or maybe that check is there to give the possibility to invalidate a cache entry? Like:
```php
$f3->set('foo,'bar',3600);
$f3->set('foo','baz',0);//invalidate cache entry
```
In which case, we could maybe find an alternative to this? Like a 4th `$force` parameter, or a special `-1` value.

**Comment by bcosca** [comment]
`if (!$this->dsn) return FALSE;` is simply for checking if `CACHE` is disabled.

**Comment by ikkez** [comment]
I think this [line](https://github.com/bcosca/fatfree-core/blob/master/base.php#L370)
`if ($cache->exists($hash=$this->hash($key).'.var') || $ttl)`
updates the cache entry, using its original expire time. From the [API docs](http://fatfreeframework.com/base#Cachingproperties):
> If the $ttl parameter is > 0, and the framework cache engine is enabled, the specified variable will be cached for $ttl seconds. Already cached vars will be updated by reusing the old expiration time.

Especially the 2nd part is interesting. I guess that the cache entry is updated using the old expiration time when `$ttl=0` but the `$cache->exists` check is true and if `$ttl>0` it always get a new expiration time and is definitly cached.

Nevertheless the caching mechanism is good here, I think it's not the set method which is the issue, but the mset for locales. Nearly everything what `set` does is not relevant for importing dictionary files. That's why I think a dumb import of them into the hive would be fast and enought.

**Comment by eazuka** [comment]
Has @ikkez proposal above been adopted/agreed on for solving the slowness issue for bigger lexicon files?

**Comment by ikkez** [comment]
since we have lexicon caching now (https://github.com/bcosca/fatfree-core/commit/4db04fafb361a19ec6df72655932922b125bae46) it's already improved at reading and parsing the dictionary files. But skipping the set method at this point could probably speed up things a lot more.
