### ISSUE TITLE
IP Change vs Session Persistence

### ISSUE THREAD

**Issue by binarygeotech** [bcosca/fatfree-core#97]
I've been facing this challenge for a while. When a user has been authenticated, session data has been set and the IP suddenly changed, the user will be asked to login again, how can I keep the session persistence if the IP changes.

And also, I've seen some web apps that gave the option to make session active even when IP changed and the user haven't logged in. Is that a feasible implementation?

**Comment by Rayne** [comment]
You could define a custom handler for suspicious users which doesn't terminate sessions on IP changes:

* [Event `onsuspect`](http://fatfreeframework.com/session#onsuspect)
* [Implementation (e.g. Cache-Backend))](https://github.com/bcosca/fatfree-core/blob/09506e76dc774e5582fc4489f54367d63105ccb5/session.php#L68-L74)

**Comment by binarygeotech** [comment]
Thanks, problem solved
