### ISSUE TITLE
handle binary PDO types

### ISSUE THREAD

**Issue by ikkez** [bcosca/fatfree-core#99]
Just for the record so we don't forget this: From an issue on SO http://stackoverflow.com/questions/33654379/bytea-retrival-via-fat-free-framework-sql-data-mapper
there was a demand to handle files in the database. Therefore an adjustment in some db->value and db->type was needed. I'm not sure if `PDO::PARAM_LOB` is available in every pdo driver, if yes maybe we can just add this here. Otherwise we could just return the value without any type-casting, so custom PDO types, which cannot be resolved by the schema method, can be used in the mapper when manually defining them.

**Comment by xfra35** [comment]
Looks like this constant [is not](https://github.com/php/php-src/blob/620daef1e253dc841f5dcb24976e5378c296e8cd/ext/pdo/pdo_dbh.c#L1408) driver-specific, so we can add it to the `$db->value()` method :+1: 

While being at it, shouldn't we also handle it in the `$db->type()` method? In order to have [this kind](http://php.net/manual/en/pdo.lobs.php#example-991) of example working. I believe the matching PHP type would be `resource`.

**Comment by xfra35** [comment]
If we do so, I guess we can as well patch `$mapper->type()` =)

**Comment by ikkez** [comment]
works. sample:

```php

$f3->route('GET /file-db-test',function( Base $f3, $params) {

	$f3->set('DB', new \DB\SQL('mysql:host=localhost;port=3306;dbname=fatfree', 'fatfree', ''));
//	$f3->set('DB', new \DB\SQL('sqlite:data/sqlite.db'));
//	$f3->set('DB', new \DB\SQL('pgsql:host=localhost;dbname=fatfree', 'fatfree', 'fatfree'));

	$schema = new \DB\SQL\Schema($f3->DB);
	if (!in_array('file_db',$schema->getTables())) {
		$table = $schema->createTable('file_db');
		$table->addColumn('name')->type_varchar();
		$table->addColumn('file')->type_blob();
		$table->build();
	}

	if ($f3->get('GET.action') == 'save') {
		// works both
//		$southpark = fopen('ui/images/south-park.jpg', 'rb');
		$southpark = file_get_contents("ui/images/south-park.jpg");
		$mapper = new \DB\SQL\Mapper($f3->DB, 'file_db');
		$mapper->name = 'South Park';
		$mapper->file = $southpark;
		$mapper->save();
	}

	if ($f3->get('GET.action') == 'view') {
		$mapper = new \DB\SQL\Mapper($f3->DB, 'file_db');
		$mapper->load(array('name = ?','South Park'));
		header("Content-Type: image/jpeg");
		if (is_resource($mapper->file))
			fpassthru($mapper->file); // pgsql
		else
			echo ($mapper->file); // mysql, sqlite
	}

	if ($f3->get('GET.action') == 'view2') {
		header("Content-Type: image/jpeg");
		$result = $f3->DB->exec('select * from file_db where name = ?',
			array(1=>'South Park'));
		if (is_resource($result[0]['file']))
			fpassthru($result[0]['file']); // pgsql
		else
			echo $result[0]['file']; // mysql, sqlite
	}

});
```

tested with mysql, sqlite and postgresql. sql server requires addional conversion, as it's saved as hex value internally and makes your like hard. I suggest to use a usual varchar(max) for sqlsrv (it's up to 2GB) instead of varbinary if you can,.. otherwise good luck.
